### ISSUE TITLE
Dependency error at devenv

### ISSUE THREAD

**Issue by L-Ryland** [apitable/apitable#1082]
**Describe the bug**
On my local env cannot create unless `USE_NATIVE_MODULE=1` is commented out. But on devenv it runs into error

**To Reproduce**
1. Go to `.env`
2. `USE_NATIVE_MODULE=1` to `#USE_NATIVE_MODULE=1`
3. 
   ```shell
   > make devenv
   > 2
   ```

**Expected behavior**
```shell
[5:10:56 AM] Starting compilation in watch mode...
2023-07-16 13:10:56 
2023-07-16 13:11:22 DeprecationWarning: 'getMutableClone' has been deprecated since v4.0.0. Use an appropriate `factory.update...` method instead, use `setCommentRange` or `setSourceMapRange`, and avoid setting `parent`.
2023-07-16 13:11:22 DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.
2023-07-16 13:11:51 [5:11:51 AM] Found 0 errors. Watching for file changes.
2023-07-16 13:11:51 
2023-07-16 13:12:05 Initialized snowflake: machine ID: 0x268
2023-07-16 13:12:05 start load language zh-CN
2023-07-16 13:12:05 language package keys:  [
2023-07-16 13:12:05   'ar-SA', 'de-DE',
2023-07-16 13:12:05   'en-US', 'es-ES',
2023-07-16 13:12:05   'fr-FR', 'it-IT',
2023-07-16 13:12:05   'ja-JP', 'ko-KR',
2023-07-16 13:12:05   'ru-RU', 'zh-CN',
2023-07-16 13:12:05   'zh-HK'
2023-07-16 13:12:05 ]
2023-07-16 13:12:07 No reducer provided for key "hooks"
2023-07-16 13:12:07 No reducer provided for key "billing"
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [NestFactory] Starting Nest application...
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] AppModule dependencies initialized +240ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] EnvConfigModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] QueueDynamicModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] RedisModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] JaegerDynamicModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] SchedTaskDynamicModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] DatabaseModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] AssetModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] AlarmDynamicModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] SubscriptionDynamicModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] EmbedDynamicModule dependencies initialized +6ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] AiDynamicModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] FusionApiDynamicModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +4ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] RedisModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] ClientsModule dependencies initialized +64ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] TerminusModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +13ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] CacheModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] ClientsModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] HttpModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] WinstonModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] I18nModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] GrpcClientModule dependencies initialized +5ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] CommandModule dependencies initialized +0ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM     LOG [InstanceLoader] GrpcClientModule dependencies initialized +3ms
2023-07-16 13:12:18 [Nest] 487  - 07/16/2023, 5:12:18 AM   ERROR [ExceptionHandler] Cannot read properties of undefined (reading 'create')
2023-07-16 13:12:18 TypeError: Cannot read properties of undefined (reading 'create')
2023-07-16 13:12:18     at new NativeService (/devenv/packages/room-server/src/shared/services/native/native.service.ts:21:69)
2023-07-16 13:12:18     at Injector.instantiateClass (/devenv/node_modules/@nestjs/core/injector/injector.js:300:19)
2023-07-16 13:12:18     at callback (/devenv/node_modules/@nestjs/core/injector/injector.js:48:41)
2023-07-16 13:12:18     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-07-16 13:12:18     at Injector.resolveConstructorParams (/devenv/node_modules/@nestjs/core/injector/injector.js:124:24)
2023-07-16 13:12:18     at Injector.loadInstance (/devenv/node_modules/@nestjs/core/injector/injector.js:52:9)
2023-07-16 13:12:18     at Injector.loadProvider (/devenv/node_modules/@nestjs/core/injector/injector.js:74:9)
2023-07-16 13:12:18     at async Promise.all (index 6)
2023-07-16 13:12:18     at InstanceLoader.createInstancesOfProviders (/devenv/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
2023-07-16 13:12:18     at /devenv/node_modules/@nestjs/core/injector/instance-loader.js:29:13
2023-07-16 13:12:18     at async Promise.all (index 2)
2023-07-16 13:12:18     at InstanceLoader.createInstances (/devenv/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
2023-07-16 13:12:18     at InstanceLoader.createInstancesOfDependencies (/devenv/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
2023-07-16 13:12:18     at /devenv/node_modules/@nestjs/core/nest-factory.js:93:17
2023-07-16 13:12:18     at Function.asyncRun (/devenv/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
2023-07-16 13:12:18     at NestFactoryStatic.initialize (/devenv/node_modules/@nestjs/core/nest-factory.js:91:13)

```

**Comment by networkhermit** [comment]
I think this issue is resolved. Feel free to comment if it still occurs.
