### ISSUE TITLE
mac下编译失败，这个如何解决？

### ISSUE THREAD

**Issue by beelzebub2006** [apitable/apitable#1109]
make install
yarn install && yarn build:pre

➤ YN0000: ┌ Resolution step
➤ YN0002: │ @apitable/components@workspace:packages/components doesn't provide @babel/core (pe20bd), requested by @storybook/addon-essentials
➤ YN0002: │ @apitable/components@workspace:packages/components doesn't provide @babel/core (paec1b), requested by babel-jest
➤ YN0002: │ @apitable/components@workspace:packages/components doesn't provide @storybook/client-api (p06a6c), requested by @storybook/testing-react
➤ YN0002: │ @apitable/components@workspace:packages/components doesn't provide babel-loader (pab0c5), requested by @storybook/addon-essentials
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p1bced) with version 18.2.0, which doesn't satisfy what @storybook/theming requests
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p147a1) with version 18.2.0, which doesn't satisfy what @storybook/addons requests
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p5d3b8) with version 18.2.0, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p727e8) with version 18.2.0, which doesn't satisfy what @storybook/addon-docs and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p18a67) with version 18.2.0, which doesn't satisfy what @storybook/addon-a11y and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p94259) with version 18.2.0, which doesn't satisfy what @storybook/addon-essentials and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p51831) with version 18.2.0, which doesn't satisfy what @storybook/addon-links requests
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p23ba1) with version 18.2.0, which doesn't satisfy what @storybook/react and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components provides react-dom (p02fa5) with version 18.2.0, which doesn't satisfy what react-laag requests
➤ YN0002: │ @apitable/components@workspace:packages/components [02716] doesn't provide @babel/core (p68868), requested by babel-jest
➤ YN0002: │ @apitable/components@workspace:packages/components [02716] doesn't provide @babel/core (p19f8f), requested by @storybook/addon-essentials
➤ YN0002: │ @apitable/components@workspace:packages/components [02716] doesn't provide @storybook/client-api (p2f45a), requested by @storybook/testing-react
➤ YN0002: │ @apitable/components@workspace:packages/components [02716] doesn't provide babel-loader (p717e8), requested by @storybook/addon-essentials
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p41d03) with version 18.2.0, which doesn't satisfy what @storybook/theming requests
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p674fa) with version 18.2.0, which doesn't satisfy what @storybook/addons requests
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p3472c) with version 18.2.0, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (pb7272) with version 18.2.0, which doesn't satisfy what @storybook/addon-docs and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p9a993) with version 18.2.0, which doesn't satisfy what @storybook/addon-a11y and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p939a7) with version 18.2.0, which doesn't satisfy what @storybook/addon-essentials and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p6b2b2) with version 18.2.0, which doesn't satisfy what @storybook/addon-links requests
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p28372) with version 18.2.0, which doesn't satisfy what @storybook/react and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [02716] provides react-dom (p27af4) with version 18.2.0, which doesn't satisfy what react-laag requests
➤ YN0002: │ @apitable/components@workspace:packages/components [6eb87] doesn't provide @babel/core (p631c5), requested by @storybook/addon-essentials
➤ YN0002: │ @apitable/components@workspace:packages/components [6eb87] doesn't provide @babel/core (p373e5), requested by babel-jest
➤ YN0002: │ @apitable/components@workspace:packages/components [6eb87] doesn't provide @storybook/client-api (p20da0), requested by @storybook/testing-react
➤ YN0002: │ @apitable/components@workspace:packages/components [6eb87] doesn't provide babel-loader (p16728), requested by @storybook/addon-essentials
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (pe6920) with version 18.2.0, which doesn't satisfy what @storybook/theming requests
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (p1b825) with version 18.2.0, which doesn't satisfy what @storybook/addons requests
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (p92a42) with version 18.2.0, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (p1f9fd) with version 18.2.0, which doesn't satisfy what @storybook/addon-docs and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (p51a21) with version 18.2.0, which doesn't satisfy what @storybook/addon-a11y and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (pec9f1) with version 18.2.0, which doesn't satisfy what @storybook/addon-essentials and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (p8764c) with version 18.2.0, which doesn't satisfy what @storybook/addon-links requests
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (p9e271) with version 18.2.0, which doesn't satisfy what @storybook/react and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [6eb87] provides react-dom (p5cdeb) with version 18.2.0, which doesn't satisfy what react-laag requests
➤ YN0002: │ @apitable/components@workspace:packages/components [f0813] doesn't provide @babel/core (p17c11), requested by babel-jest
➤ YN0002: │ @apitable/components@workspace:packages/components [f0813] doesn't provide @babel/core (pc5587), requested by @storybook/addon-essentials
➤ YN0002: │ @apitable/components@workspace:packages/components [f0813] doesn't provide @storybook/client-api (pd561e), requested by @storybook/testing-react
➤ YN0002: │ @apitable/components@workspace:packages/components [f0813] doesn't provide babel-loader (p84c3a), requested by @storybook/addon-essentials
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (pd1b0c) with version 18.2.0, which doesn't satisfy what @storybook/theming requests
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (pb9cdf) with version 18.2.0, which doesn't satisfy what @storybook/addons requests
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (p38397) with version 18.2.0, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (p3c534) with version 18.2.0, which doesn't satisfy what @storybook/addon-docs and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (p52fc6) with version 18.2.0, which doesn't satisfy what @storybook/addon-a11y and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (pbc860) with version 18.2.0, which doesn't satisfy what @storybook/addon-essentials and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (p77b68) with version 18.2.0, which doesn't satisfy what @storybook/addon-links requests
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (pa873c) with version 18.2.0, which doesn't satisfy what @storybook/react and some of its descendants request
➤ YN0060: │ @apitable/components@workspace:packages/components [f0813] provides react-dom (p059a1) with version 18.2.0, which doesn't satisfy what react-laag requests
➤ YN0060: │ @apitable/core@workspace:packages/core provides @types/jest (p0be19) with version 29.2.1, which doesn't satisfy what ts-jest requests
➤ YN0060: │ @apitable/core@workspace:packages/core provides jest (p6537f) with version 29.2.2, which doesn't satisfy what ts-jest requests
➤ YN0002: │ @apitable/cypress@workspace:packages/cypress doesn't provide @types/node (pd76ec), requested by ts-node
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide @babel/core (pda7bf), requested by babel-jest
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide @babel/core (p771a0), requested by babel-loader
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides @types/react (p29a2a) with version 18.0.28, which doesn't satisfy what @apitable/components and some of its descendants request
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide prop-types (pac720), requested by react-contextmenu
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p4d831) with version 18.2.0, which doesn't satisfy what react-highlight-words requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (pb167f) with version 18.2.0, which doesn't satisfy what emoji-mart requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (paf81b) with version 18.2.0, which doesn't satisfy what react-virtualized-auto-sizer requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (pf8bef) with version 18.2.0, which doesn't satisfy what @apitable/components and some of its descendants request
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p559e4) with version 18.2.0, which doesn't satisfy what @apitable/react-flow and some of its descendants request
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p74913) with version 18.2.0, which doesn't satisfy what html-react-parser requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p1857d) with version 18.2.0, which doesn't satisfy what react-beautiful-dnd and some of its descendants request
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p93a48) with version 18.2.0, which doesn't satisfy what react-contextmenu requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p337cd) with version 18.2.0, which doesn't satisfy what react-custom-scrollbars requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p6c86c) with version 18.2.0, which doesn't satisfy what react-device-detect requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p1bca4) with version 18.2.0, which doesn't satisfy what react-pdf requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p6b896) with version 18.2.0, which doesn't satisfy what react-sortable-hoc requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p3907d) with version 18.2.0, which doesn't satisfy what react-split-pane requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react (p1db73) with version 18.2.0, which doesn't satisfy what use-long-press requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (p6813c) with version 18.2.0, which doesn't satisfy what react-virtualized-auto-sizer requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (p4adcb) with version 18.2.0, which doesn't satisfy what @apitable/react-flow and some of its descendants request
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (p2f3b1) with version 18.2.0, which doesn't satisfy what react-contextmenu requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (pa1472) with version 18.2.0, which doesn't satisfy what react-custom-scrollbars requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (pba21f) with version 18.2.0, which doesn't satisfy what react-device-detect requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (p57740) with version 18.2.0, which doesn't satisfy what react-pdf requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (pb7cfc) with version 18.2.0, which doesn't satisfy what react-sortable-hoc requests
➤ YN0060: │ @apitable/datasheet@workspace:packages/datasheet provides react-dom (p9ea29) with version 18.2.0, which doesn't satisfy what react-split-pane requests
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide webpack (p264a4), requested by babel-loader
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide webpack (p3f6c5), requested by eslint-webpack-plugin
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide webpack (p7d89c), requested by fork-ts-checker-webpack-plugin
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide webpack (p1210a), requested by less-loader
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide webpack (p38b5b), requested by raw-loader
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide webpack (p2594c), requested by react-dev-utils
➤ YN0002: │ @apitable/datasheet@workspace:packages/datasheet doesn't provide webpack (pdddac), requested by worker-plugin
➤ YN0002: │ @apitable/icons@workspace:packages/icons doesn't provide react-dom (pf11d2), requested by styled-components
➤ YN0002: │ @apitable/icons@workspace:packages/icons doesn't provide react-is (p20a6a), requested by styled-components
➤ YN0002: │ @apitable/icons@workspace:packages/icons [f0813] doesn't provide react-dom (pcc0fa), requested by styled-components
➤ YN0002: │ @apitable/icons@workspace:packages/icons [f0813] doesn't provide react-is (pfaf43), requested by styled-components
➤ YN0002: │ @apitable/icons@workspace:packages/icons [fdf21] doesn't provide react-dom (pa97dc), requested by styled-components
➤ YN0002: │ @apitable/icons@workspace:packages/icons [fdf21] doesn't provide react-is (p6a6d6), requested by styled-components
➤ YN0060: │ @apitable/room-server@workspace:packages/room-server provides @nestjs/event-emitter (p9e6f0) with version 2.0.0, which doesn't satisfy what @metinseylan/nestjs-opentelemetry requests
➤ YN0002: │ @apitable/room-server@workspace:packages/room-server doesn't provide @opentelemetry/api (pf58cc), requested by @opentelemetry/auto-instrumentations-node
➤ YN0002: │ @apitable/room-server@workspace:packages/room-server doesn't provide @opentelemetry/api (pac897), requested by @opentelemetry/exporter-jaeger
➤ YN0060: │ @apitable/room-server@workspace:packages/room-server provides @types/jest (p118c3) with version 25.2.3, which doesn't satisfy what ts-jest requests
➤ YN0002: │ @apitable/widget-sdk@workspace:packages/widget-sdk doesn't provide @babel/core (p8c16e), requested by babel-jest
➤ YN0060: │ @apitable/widget-sdk@workspace:packages/widget-sdk provides babel-jest (p518de) with version 26.6.3, which doesn't satisfy what ts-jest requests
➤ YN0002: │ @apitable/widget-sdk@workspace:packages/widget-sdk doesn't provide react-is (pae3ec), requested by styled-components
➤ YN0060: │ @apitable/widget-sdk@workspace:packages/widget-sdk provides typescript (pfb10c) with version 4.8.2, which doesn't satisfy what typedoc requests
➤ YN0002: │ @apitable/widget-sdk@workspace:packages/widget-sdk [f0813] doesn't provide @babel/core (pee352), requested by babel-jest
➤ YN0060: │ @apitable/widget-sdk@workspace:packages/widget-sdk [f0813] provides babel-jest (p74c68) with version 26.6.3, which doesn't satisfy what ts-jest requests
➤ YN0002: │ @apitable/widget-sdk@workspace:packages/widget-sdk [f0813] doesn't provide react-is (p575dc), requested by styled-components
➤ YN0060: │ @apitable/widget-sdk@workspace:packages/widget-sdk [f0813] provides typescript (p954ab) with version 4.8.2, which doesn't satisfy what typedoc requests
➤ YN0002: │ @aws-sdk/client-s3@npm:3.47.0 doesn't provide @aws-sdk/signature-v4-crt (pbc21d), requested by @aws-sdk/middleware-sdk-s3
➤ YN0002: │ @golevelup/nestjs-rabbitmq@npm:2.2.0 doesn't provide @nestjs/common (p0ea8f), requested by @golevelup/nestjs-modules
➤ YN0002: │ @golevelup/nestjs-rabbitmq@npm:2.2.0 doesn't provide rxjs (p8d249), requested by @golevelup/nestjs-modules
➤ YN0002: │ @mdx-js/loader@npm:1.6.22 doesn't provide react (p12550), requested by @mdx-js/react
➤ YN0060: │ @metinseylan/nestjs-opentelemetry@npm:2.0.7 [628d3] provides @opentelemetry/api (pc3ec0) with version 1.4.0, which doesn't satisfy what @opentelemetry/host-metrics and some of its descendants request
➤ YN0060: │ @metinseylan/nestjs-opentelemetry@npm:2.0.7 [628d3] provides @opentelemetry/api (p12042) with version 1.4.0, which doesn't satisfy what @opentelemetry/sdk-node and some of its descendants request
➤ YN0002: │ @nestjs/swagger@npm:5.1.4 [628d3] doesn't provide class-transformer (p5479d), requested by @nestjs/mapped-types
➤ YN0002: │ @nestjs/swagger@npm:5.1.4 [628d3] doesn't provide class-validator (p4d112), requested by @nestjs/mapped-types
➤ YN0002: │ @storybook/addon-essentials@npm:6.3.6 [3bc0e] doesn't provide @storybook/components (p848d2), requested by @storybook/addon-measure
➤ YN0002: │ @storybook/addon-essentials@npm:6.3.6 [3bc0e] doesn't provide @storybook/core-events (p8c314), requested by @storybook/addon-measure
➤ YN0002: │ @storybook/addon-essentials@npm:6.3.6 [3bc0e] doesn't provide @storybook/theming (p05100), requested by @storybook/addon-measure
➤ YN0002: │ @storybook/addon-essentials@npm:6.3.6 [fdf21] doesn't provide @storybook/components (p1f24b), requested by @storybook/addon-measure
➤ YN0002: │ @storybook/addon-essentials@npm:6.3.6 [fdf21] doesn't provide @storybook/core-events (p00c7b), requested by @storybook/addon-measure
➤ YN0002: │ @storybook/addon-essentials@npm:6.3.6 [fdf21] doesn't provide @storybook/theming (p2ac0a), requested by @storybook/addon-measure
➤ YN0002: │ @storybook/addon-notes@npm:5.3.21 [3bc0e] doesn't provide react-dom (p2c5c4), requested by @storybook/router
➤ YN0002: │ @storybook/addon-notes@npm:5.3.21 [3bc0e] doesn't provide react-dom (p07148), requested by @storybook/theming
➤ YN0002: │ @storybook/addon-notes@npm:5.3.21 [3bc0e] doesn't provide regenerator-runtime (p8d9e0), requested by @storybook/api
➤ YN0002: │ @storybook/addon-notes@npm:5.3.21 [fdf21] doesn't provide react-dom (p51d95), requested by @storybook/router
➤ YN0002: │ @storybook/addon-notes@npm:5.3.21 [fdf21] doesn't provide react-dom (p420be), requested by @storybook/theming
➤ YN0002: │ @storybook/addon-notes@npm:5.3.21 [fdf21] doesn't provide regenerator-runtime (p25c18), requested by @storybook/api
➤ YN0002: │ @storybook/addons@npm:5.3.21 doesn't provide regenerator-runtime (p23d0c), requested by @storybook/api
➤ YN0002: │ @storybook/api@npm:5.3.21 [95e28] doesn't provide react-dom (p708bc), requested by @reach/router
➤ YN0002: │ @storybook/api@npm:5.3.21 [95e28] doesn't provide react-dom (pcdcf3), requested by @storybook/router
➤ YN0002: │ @storybook/api@npm:5.3.21 [95e28] doesn't provide react-dom (pd04d4), requested by @storybook/theming
➤ YN0002: │ @storybook/core@npm:6.3.6 [2fba1] doesn't provide webpack (p89d72), requested by @storybook/core-client
➤ YN0002: │ @storybook/core@npm:6.3.6 [60ade] doesn't provide webpack (p7ca5d), requested by @storybook/core-client
➤ YN0002: │ @storybook/core@npm:6.3.6 [a3c4a] doesn't provide webpack (pf868c), requested by @storybook/core-client
➤ YN0002: │ @storybook/core@npm:6.3.6 [cc2f7] doesn't provide webpack (p024cb), requested by @storybook/core-client
➤ YN0002: │ @storybook/csf-tools@npm:6.3.6 doesn't provide @babel/core (pd58b6), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ @storybook/csf-tools@npm:6.3.6 doesn't provide @babel/core (p4ec35), requested by @babel/preset-env
➤ YN0002: │ @types/react-dropzone@npm:5.1.0 doesn't provide react (p4caba), requested by react-dropzone
➤ YN0002: │ antd-mobile@npm:5.24.0 [f0813] doesn't provide react-dom (p15158), requested by @react-spring/web
➤ YN0002: │ antd-mobile@npm:5.24.0 [f0813] doesn't provide react-dom (pf089a), requested by rc-field-form
➤ YN0002: │ chromatic@npm:5.10.1 doesn't provide @babel/core (pfc126), requested by @babel/preset-typescript
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react (p8a8f0), requested by rc-animate
➤ YN0002: │ rc-trigger@npm:2.6.5 doesn't provide react-dom (p1433f), requested by rc-animate
➤ YN0002: │ react-grid-layout@npm:1.2.0 doesn't provide react (pd2e61), requested by react-draggable
➤ YN0002: │ react-grid-layout@npm:1.2.0 doesn't provide react (pe7dbf), requested by react-resizable
➤ YN0002: │ react-grid-layout@npm:1.2.0 doesn't provide react-dom (p96991), requested by react-draggable
➤ YN0002: │ react-grid-layout@npm:1.2.0 doesn't provide react-dom (pd8681), requested by react-resizable
➤ YN0002: │ react-pdf@npm:5.4.0 [f0813] doesn't provide webpack (p20428), requested by file-loader
➤ YN0002: │ react-pdf@npm:5.4.0 [f0813] doesn't provide worker-loader (pd85ab), requested by pdfjs-dist
➤ YN0060: │ root@workspace:. provides @typescript-eslint/eslint-plugin (p639c2) with version 5.42.0, which doesn't satisfy what eslint-config-react-app requests
➤ YN0060: │ root@workspace:. provides @typescript-eslint/parser (p575f0) with version 5.42.0, which doesn't satisfy what eslint-config-react-app requests
➤ YN0060: │ root@workspace:. provides eslint (p63cfc) with version 7.32.0, which doesn't satisfy what eslint-config-react-app requests
➤ YN0060: │ root@workspace:. provides eslint-plugin-flowtype (pf2b86) with version 5.2.0, which doesn't satisfy what eslint-config-react-app requests
➤ YN0060: │ root@workspace:. provides eslint-plugin-react-hooks (p2fb03) with version 4.6.0, which doesn't satisfy what eslint-config-react-app requests
➤ YN0002: │ root@workspace:. doesn't provide webpack (pf37c2), requested by eslint-loader
➤ YN0002: │ storybook-addon-designs@npm:6.1.0 doesn't provide react (p0b861), requested by @figspec/react
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 955ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 301ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2s 299ms
➤ YN0000: Done with warnings in 4s 829ms
➤ YN0000: Internal Error: Command failed: cargo build --release
➤ YN0000:     at checkExecSyncError (node:child_process:828:11)
➤ YN0000:     at Object.execSync (node:child_process:899:15)
➤ YN0000:     at BuildCommand.<anonymous> (/Users/jackiewang/Work/Demo/apitable/node_modules/@napi-rs/cli/scripts/index.js:11503:30)
➤ YN0000:     at Generator.next (<anonymous>)
➤ YN0000:     at /Users/jackiewang/Work/Demo/apitable/node_modules/@napi-rs/cli/scripts/index.js:3512:71
➤ YN0000:     at new Promise (<anonymous>)
➤ YN0000:     at __awaiter$1 (/Users/jackiewang/Work/Demo/apitable/node_modules/@napi-rs/cli/scripts/index.js:3508:12)
➤ YN0000:     at BuildCommand.execute (/Users/jackiewang/Work/Demo/apitable/node_modules/@napi-rs/cli/scripts/index.js:11283:16)
➤ YN0000:     at BuildCommand.validateAndExecute (/Users/jackiewang/Work/Demo/apitable/node_modules/@napi-rs/cli/scripts/index.js:2038:37)
➤ YN0000:    Compiling mysql_common v0.30.6
➤ YN0000:    Compiling pretty_env_logger v0.4.0
➤ YN0000:    Compiling webpki-roots v0.23.1
➤ YN0000:    Compiling pem v2.0.1
➤ YN0000:    Compiling tracing-log v0.1.3
➤ YN0000:    Compiling sha-1 v0.10.1
➤ YN0000:    Compiling iana-time-zone v0.1.56
➤ YN0000:    Compiling twox-hash v1.6.3
➤ YN0000:    Compiling tokio-stream v0.1.14
➤ YN0000:    Compiling sharded-slab v0.1.4
➤ YN0000:    Compiling float-cmp v0.9.0
➤ YN0000:    Compiling webpki v0.22.0
➤ YN0000:    Compiling ctor v0.2.0
➤ YN0000:    Compiling shaku_derive v0.6.1
➤ YN0000: error[E0432]: unresolved import `bitflags::Flags`
➤ YN0000:  --> /Users/jackiewang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mysql_common-0.30.6/src/misc/raw/flags.rs:9:5
➤ YN0000:   |
➤ YN0000: 9 | use bitflags::Flags;
➤ YN0000:   |     ^^^^^^^^^^^^^^^ no `Flags` in the root
➤ YN0000:
➤ YN0000:    Compiling thread_local v1.1.7
➤ YN0000:    Compiling socket2 v0.5.3
➤ YN0000:    Compiling encoding_rs v0.8.32
➤ YN0000:    Compiling napi-sys v2.2.3
➤ YN0000:    Compiling anymap v0.12.1
➤ YN0000:    Compiling arc-swap v1.6.0
➤ YN0000:    Compiling arcstr v1.1.5
➤ YN0000:    Compiling napi v2.13.2
➤ YN0000: error[E0220]: associated type `Bits` not found for `T`
➤ YN0000:   --> /Users/jackiewang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mysql_common-0.30.6/src/misc/raw/flags.rs:26:41
➤ YN0000:    |
➤ YN0000: 26 | pub struct RawFlags<T: Flags, U>(pub T::Bits, PhantomData<U>);
➤ YN0000:    |                                         ^^^^ associated type `Bits` not found
➤ YN0000:
➤ YN0000: Some errors have detailed explanations: E0220, E0432.
➤ YN0000: For more information about an error, try `rustc --explain E0220`.
➤ YN0000: error: could not compile `mysql_common` (lib) due to 2 previous errors
➤ YN0000: warning: build failed, waiting for other jobs to finish...
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 27s 450ms
make: *** [install-local] Error 1

**Comment by ziqiangai** [comment]
There is a problem with the Rust module we are refactoring, you can remove the dependency on Rust in `package.json`.

https://github.com/apitable/apitable/blob/a513793f2a352eb248820d2a4c6b45d43246e103/package.json#L29C90-L29C108

**Comment by mr-kelly** [comment]
As our team member explained, this was a temporary issue caused by the refactoring of our Rust modules at the time. You can bypass this by removing the specific Rust dependencies from `package.json` as suggested, or by pulling the latest code where this build chain has been stabilized. We will close this issue for now.

---

正如我们的团队成员所解释的，这是当时我们重构 Rust 模块引起的一个临时问题。您可以通过按照建议从 `package.json` 中移除特定的 Rust 依赖项来绕过此问题，或者拉取此构建链已稳定下来的最新代码。我们将暂时关闭此 Issue。
