### ISSUE TITLE
question: server upgrade failed (all-in-one server) due to Liquibase  Validation Failed

### ISSUE THREAD

**Issue by lumos0** [apitable/apitable#1182]
## Any questions?
I tried to upgrade from 0.20.0-alpha to 0.99.0-alpha following the instruction you provided in
https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW
but failed.

As you can see from the logs below, the errors seem to be related to database changes between versions.

**How should I upgrade correctly?**

or

if upgrades are not supported between specific versions, could you provide more explicit instructions 

## Error log

```
5|backend-server  | Starting Liquibase at 08:10:05 (version 4.8.0 #1581 built at 2022-02-18 21:43+0000)
5|backend-server  | Liquibase Version: 4.8.0
5|backend-server  | Liquibase Community 4.8.0 by Liquibase
5|backend-server  | Successfully released all database change log locks for 'root@127.0.0.1@jdbc:mysql://mysql:3306/apitable?characterEncoding=utf8&autoReconnect=true&useSSL=true'
5|backend-server  | Liquibase command 'releaseLocks' was executed successfully.
5|backend-server  | ####################################################
5|backend-server  | ##   _     _             _ _                      ##
5|backend-server  | ##  | |   (_)           (_) |                     ##
5|backend-server  | ##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
5|backend-server  | ##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
5|backend-server  | ##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
5|backend-server  | ##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
5|backend-server  | ##              | |                               ##
5|backend-server  | ##              |_|                               ##
5|backend-server  | ##                                                ## 
5|backend-server  | ##  Get documentation at docs.liquibase.com       ##
5|backend-server  | ##  Get certified courses at learn.liquibase.com  ## 
5|backend-server  | ##  Free schema change activity reports at        ##
5|backend-server  | ##      https://hub.liquibase.com                 ##
5|backend-server  | ##                                                ##
5|backend-server  | ####################################################
5|backend-server  | Starting Liquibase at 08:10:07 (version 4.8.0 #1581 built at 2022-02-18 21:43+0000)
5|backend-server  | Liquibase Version: 4.8.0
5|backend-server  | Liquibase Community 4.8.0 by Liquibase
5|backend-server  | [2023-08-07 08:10:09] SEVERE [liquibase.integration] Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | at liquibase.command.CommandScope.execute(CommandScope.java:163)
5|backend-server  | at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
5|backend-server  | at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
5|backend-server  | at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
5|backend-server  | at picocli.CommandLine.access$1300(CommandLine.java:145)
5|backend-server  | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
5|backend-server  | at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
5|backend-server  | at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
5|backend-server  | at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
5|backend-server  | at picocli.CommandLine.execute(CommandLine.java:2078)
5|backend-server  | at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:165)
5|backend-server  | at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
5|backend-server  | at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
5|backend-server  | Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | at liquibase.integration.commandline.Main$1.run(Main.java:443)
5|backend-server  | at liquibase.integration.commandline.Main$1.run(Main.java:221)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:165)
5|backend-server  | at liquibase.integration.commandline.Main.run(Main.java:221)
5|backend-server  | at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
5|backend-server  | at liquibase.command.CommandScope.execute(CommandScope.java:157)
5|backend-server  | ... 14 more
5|backend-server  | Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296)
5|backend-server  | at liquibase.Liquibase.lambda$update$1(Liquibase.java:231)
5|backend-server  | at liquibase.Scope.lambda$child$0(Scope.java:180)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:179)
5|backend-server  | at liquibase.Scope.child(Scope.java:158)
5|backend-server  | at liquibase.Liquibase.runInScope(Liquibase.java:2405)
5|backend-server  | at liquibase.Liquibase.update(Liquibase.java:211)
5|backend-server  | at liquibase.Liquibase.update(Liquibase.java:197)
5|backend-server  | at liquibase.integration.commandline.Main.doMigration(Main.java:1871)
5|backend-server  | at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
5|backend-server  | at liquibase.Scope.lambda$child$0(Scope.java:180)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:179)
5|backend-server  | at liquibase.Scope.child(Scope.java:158)
5|backend-server  | at liquibase.integration.commandline.Main$1.run(Main.java:397)
5|backend-server  | ... 20 more
5|backend-server  | Unexpected error running Liquibase: Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | at liquibase.command.CommandScope.execute(CommandScope.java:163)
5|backend-server  | at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
5|backend-server  | at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
5|backend-server  | at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
5|backend-server  | at picocli.CommandLine.access$1300(CommandLine.java:145)
5|backend-server  | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
5|backend-server  | at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
5|backend-server  | at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
5|backend-server  | at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
5|backend-server  | at picocli.CommandLine.execute(CommandLine.java:2078)
5|backend-server  | at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:165)
5|backend-server  | at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
5|backend-server  | at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
5|backend-server  | Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | at liquibase.integration.commandline.Main$1.run(Main.java:443)
5|backend-server  | at liquibase.integration.commandline.Main$1.run(Main.java:221)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:165)
5|backend-server  | at liquibase.integration.commandline.Main.run(Main.java:221)
5|backend-server  | at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
5|backend-server  | at liquibase.command.CommandScope.execute(CommandScope.java:157)
5|backend-server  | ... 14 more
5|backend-server  | Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
5|backend-server  |      1 change sets check sum
5|backend-server  |           db/changelog/0.13/20220829_changeset.xml::V0.13-20220829-004::wuyitao was: 8:395a517c7d4e8657e5ed51cfb6de4cde but is now: 8:a9554f0cf678ee424c13f6b0b1bdfae4
5|backend-server  | at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:296)
5|backend-server  | at liquibase.Liquibase.lambda$update$1(Liquibase.java:231)
5|backend-server  | at liquibase.Scope.lambda$child$0(Scope.java:180)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:179)
5|backend-server  | at liquibase.Scope.child(Scope.java:158)
5|backend-server  | at liquibase.Liquibase.runInScope(Liquibase.java:2405)
5|backend-server  | at liquibase.Liquibase.update(Liquibase.java:211)
5|backend-server  | at liquibase.Liquibase.update(Liquibase.java:197)
5|backend-server  | at liquibase.integration.commandline.Main.doMigration(Main.java:1871)
5|backend-server  | at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:398)
5|backend-server  | at liquibase.Scope.lambda$child$0(Scope.java:180)
5|backend-server  | at liquibase.Scope.child(Scope.java:189)
5|backend-server  | at liquibase.Scope.child(Scope.java:179)
5|backend-server  | at liquibase.Scope.child(Scope.java:158)
5|backend-server  | at liquibase.integration.commandline.Main$1.run(Main.java:397)
5|backend-server  | ... 20 more
```

**Comment by networkhermit** [comment]
Could you confirm whether new installation of all-in-one 0.99.0-alpha works? By the way, the all-in-one version is not as stable as the docker compose version.

**Comment by lumos0** [comment]
> Could you confirm whether new installation of all-in-one 0.99.0-alpha works? By the way, the all-in-one version is not as stable as the docker compose version.

New installation of all-in-one 0.99.0-alpha works well.

btw,  I noticed that the size of the data directory before upgrade was about 1.1GB, and it shrank to 700+ MB just after 
new version image had started  ( `docker run -d -v {data_dir}:/apitable -p 80:80 --name apitable_0.99 apitable/all-in-one:latest` )

I guess the upgrade process needs to keep the database schema updated but not reinitialize the data.


---
#### data directory diff
 .data/                                -- data dir just after new version image started
.data.backupForUpgrade   -- old data dir
```
Files .data/minio/data/.minio.sys/buckets/.bloomcycle.bin/xl.meta and .data.backupForUpgrade/minio/data/.minio.sys/buckets/.bloomcycle.bin/xl.meta differ
Files .data/minio/data/.minio.sys/buckets/.tracker.bin and .data.backupForUpgrade/minio/data/.minio.sys/buckets/.tracker.bin differ
Files .data/minio/data/.minio.sys/buckets/.usage-cache.bin/xl.meta and .data.backupForUpgrade/minio/data/.minio.sys/buckets/.usage-cache.bin/xl.meta differ
Files .data/minio/data/.minio.sys/buckets/.usage.json/xl.meta and .data.backupForUpgrade/minio/data/.minio.sys/buckets/.usage.json/xl.meta differ
Files .data/minio/data/.minio.sys/buckets/assets/.usage-cache.bin/xl.meta and .data.backupForUpgrade/minio/data/.minio.sys/buckets/assets/.usage-cache.bin/xl.meta differ
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 02e2035a-bb97-4214-a3d2-b49575d92a49
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 06e4d97f-8ca6-424a-94de-fc59b891f5cc
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 07b8c255-db90-48a8-9cf2-825c1ceea81b
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 0d060492-7b4c-4355-b5a9-6958a72cdf2b
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 1141b974-5b83-4c96-a14d-421dffd99566
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 1169c4f1-9c2f-4945-b121-d16185328a07
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 14fff881-080c-4c70-97e2-8aa0f5c54105
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 1b68f574-fe3a-49e1-b92b-50a9d4390f6a
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 1b6bd47b-53a7-44d9-8003-aa9a9656b4b2
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 1d5db523-18dd-4847-a309-c08cfdb846bd
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 228cb13b-9efe-4574-8732-c652212e1661
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 28e86e31-8432-460a-b2f4-34a91d7d4662
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 2a64b04d-174d-4dea-a926-0c2c66aa5b04
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 2e05558a-032e-4f25-8a8e-bd76a0c3bd39
Only in .data/minio/data/.minio.sys/tmp/.trash: 2ef6c6e0-f970-4a08-8c84-22a87a3c328d
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 2f38e9f3-19b2-4ad3-aabe-11bff647b8bd
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 3001a136-23b2-4983-83e7-040fb74a2f60
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 3025d23e-f914-4831-b76d-46ccf05fc8d3
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 3a06ed64-b246-48f2-bb78-e994247cd048
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 3cfaaf45-ff05-479e-a8cc-319f770cf611
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 41629872-5378-4acc-a16e-1c2b8d2392c1
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 4b12940b-3679-4b44-b29a-6421689b22ff
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 551a3fc5-ba26-48b1-bf13-20bcf5009e2f
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 5563a1bd-979a-4ffb-a2bd-d99ee6891e1a
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 6375ae53-ec58-4c51-a633-54e54073e53a
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 7372ba5f-30d2-4f7a-bde7-34eba4b03332
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 74bbbdfd-818b-4daa-9664-f6ec4ca961ea
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 7543b83e-9362-455f-81d0-8542b48a07d3
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 799de8de-bd60-4bc0-b2d5-22bed9ac152b
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 79c18115-05ef-4387-ab50-c7ad00e97a11
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 815dcc29-4e66-4aab-ba03-47ba3ad9d96e
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 87dfd82f-9784-4a63-b4ad-ae46fde59482
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 8b61a425-b0d6-45fa-81d2-2e7cdcb63ed4
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 91278b89-11ac-463a-88f1-de65e6241f49
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 9989eee6-c621-438e-b709-56480b3cc41c
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 9cfee8c3-07b0-4bbe-8aba-1433d04d5f1a
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: 9deff666-7941-454c-aa43-f9acc6a2b847
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: a48cc093-c9bc-4f80-8244-58ba63a266b4
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: a6559a24-1107-4f31-a200-7206e553ac6a
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: bcb5af8b-e8cf-4d75-a155-2b01f6413ca8
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: bfb3321a-87ff-4e0d-9d97-ba69faac2d06
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: c4319ec1-aaad-4013-ae1f-66e5fa2c0317
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: c617b4bc-1983-4b43-bd0c-14ef3b803e9f
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: c89a41ed-0b10-4b6b-a05e-b7618526bfcf
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: cd7ea8ae-5415-4142-8b29-b3a8ee42edbb
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: dd3bb02c-ad28-4f67-acec-7aa9117f5390
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: df17e039-bcc8-4e3e-94cd-265a73f86cc0
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: df55077c-aecf-4a14-a490-63a21196eb30
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: e1d2c350-3520-43fd-bc78-c08097f1c6fc
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: ea570d1f-339e-44a1-b0d1-08a72724b4ce
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: edf440c4-b896-4a76-b525-7e735502a6d6
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: f383c59d-7564-4cfc-b9da-fcfca2f944f3
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: f9b4459e-dcc3-42f7-8519-133d60036119
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: fa5a29e7-5256-40bf-b436-d704324b9817
Only in .data.backupForUpgrade/minio/data/.minio.sys/tmp/.trash: ffb26ad6-ca2b-41c5-b20c-84325b9e81ba
Files .data/mysql/#ib_16384_0.dblwr and .data.backupForUpgrade/mysql/#ib_16384_0.dblwr differ
Only in .data.backupForUpgrade/mysql/#innodb_redo: #ib_redo36
Files .data/mysql/#innodb_redo/#ib_redo37 and .data.backupForUpgrade/mysql/#innodb_redo/#ib_redo37 differ
Only in .data/mysql/#innodb_redo: #ib_redo68_tmp
Files .data/mysql/#innodb_temp/temp_1.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_1.ibt differ
Files .data/mysql/#innodb_temp/temp_10.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_10.ibt differ
Files .data/mysql/#innodb_temp/temp_2.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_2.ibt differ
Files .data/mysql/#innodb_temp/temp_3.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_3.ibt differ
Files .data/mysql/#innodb_temp/temp_4.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_4.ibt differ
Files .data/mysql/#innodb_temp/temp_5.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_5.ibt differ
Files .data/mysql/#innodb_temp/temp_6.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_6.ibt differ
Files .data/mysql/#innodb_temp/temp_7.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_7.ibt differ
Files .data/mysql/#innodb_temp/temp_8.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_8.ibt differ
Files .data/mysql/#innodb_temp/temp_9.ibt and .data.backupForUpgrade/mysql/#innodb_temp/temp_9.ibt differ
Files .data/mysql/apitable/apitable_db_changelog_lock.ibd and .data.backupForUpgrade/mysql/apitable/apitable_db_changelog_lock.ibd differ
Files .data/mysql/binlog.000756 and .data.backupForUpgrade/mysql/binlog.000756 differ
Only in .data/mysql: binlog.000757
Files .data/mysql/binlog.index and .data.backupForUpgrade/mysql/binlog.index differ
Files .data/mysql/ibdata1 and .data.backupForUpgrade/mysql/ibdata1 differ
Files .data/mysql/ibtmp1 and .data.backupForUpgrade/mysql/ibtmp1 differ
Files .data/mysql/mysql.ibd and .data.backupForUpgrade/mysql/mysql.ibd differ
Files .data/mysql/undo_001 and .data.backupForUpgrade/mysql/undo_001 differ
Files .data/mysql/undo_002 and .data.backupForUpgrade/mysql/undo_002 differ
Only in .data/rabbitmq: rabbit@a0b907ae3dd1
Only in .data/rabbitmq: rabbit@a0b907ae3dd1-feature_flags
Only in .data/rabbitmq: rabbit@a0b907ae3dd1-plugins-expand
Only in .data/rabbitmq: rabbit@a0b907ae3dd1.pid
Files .data/redis/appendonly.aof and .data.backupForUpgrade/redis/appendonly.aof differ
Files .data/redis/dump.rdb and .data.backupForUpgrade/redis/dump.rdb differ
```

**Comment by lumos0** [comment]
@networkhermit  any update？ 😊

**Comment by networkhermit** [comment]
@lumos0 

Please try apitable/all-in-one:v1.0.0-beta.2, I upgrade it from v0.20.0-alpha_1286 and it is working as expected.

**Comment by lumos0** [comment]
> @lumos0
> 
> Please try apitable/all-in-one:v1.0.0-beta.2, I upgrade it from v0.20.0-alpha_1286 and it is working as expected.

it works. thanks
