### ISSUE TITLE
question: 404 resource when yarn in Mac m1

### ISSUE THREAD

**Issue by BruceChar** [apitable/apitable#1215]
```
# This file contains the result of Yarn building a package (canvas@npm:2.9.1)
# Script name: install

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@20.5.0 | darwin | arm64
node-pre-gyp info check checked for "/Users/bruce/programs/apitable/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v115-darwin-unknown-arm64.tar.gz
node-pre-gyp http download proxy agent configured using: "http://127.0.0.1:7890"
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v115-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.9.1 and node@20.5.0 (node-v115 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.9.1/canvas-v2.9.1-node-v115-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@20.5.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@20.5.0 | darwin | arm64
gyp info find Python using Python version 3.11.4 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
gyp info spawn /opt/homebrew/opt/python@3.11/bin/python3.11
gyp info spawn args [
gyp info spawn args   '/Users/bruce/programs/apitable/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bruce/programs/apitable/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bruce/programs/apitable/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bruce/Library/Caches/node-gyp/20.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bruce/Library/Caches/node-gyp/20.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/bruce/programs/apitable/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/bruce/Library/Caches/node-gyp/20.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/bruce/programs/apitable/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@20.5.0 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
In file included from ../src/backend/Backend.cc:1:
In file included from ../src/backend/Backend.h:6:
In file included from ../../nan/nan.h:180:
../../nan/nan_callbacks.h:55:23: error: no member named 'AccessorSignature' in namespace 'v8'
typedef v8::Local<v8::AccessorSignature> Sig;
                  ~~~~^
In file included from ../src/backend/Backend.cc:1:
In file included from ../src/backend/Backend.h:6:
../../nan/nan.h:686:39: warning: 'IdleNotificationDeadline' is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
    return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
                                      ^
/Users/bruce/Library/Caches/node-gyp/20.5.0/include/node/v8-isolate.h:1291:3: note: 'IdleNotificationDeadline' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
/Users/bruce/Library/Caches/node-gyp/20.5.0/include/node/v8config.h:550:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
In file included from ../src/backend/Backend.cc:1:
../src/backend/Backend.h:60:14: warning: private field 'backend' is not used [-Wunused-private-field]
    Backend* backend;
             ^
2 warnings and 1 error generated.
make: *** [Release/obj.target/canvas/src/backend/Backend.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/bruce/programs/apitable/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/Users/bruce/programs/apitable/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/bruce/programs/apitable/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/bruce/programs/apitable/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
gyp ERR! cwd /Users/bruce/programs/apitable/node_modules/canvas
gyp ERR! node -v v20.5.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/homebrew/Cellar/node/20.5.0/bin/node /Users/bruce/programs/apitable/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/bruce/programs/apitable/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/bruce/programs/apitable/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/bruce/programs/apitable/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Darwin 22.3.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/20.5.0/bin/node" "/Users/bruce/programs/apitable/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/bruce/programs/apitable/node_modules/canvas
node-pre-gyp ERR! node -v v20.5.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok 
Failed to execute '/opt/homebrew/Cellar/node/20.5.0/bin/node /Users/bruce/programs/apitable/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/bruce/programs/apitable/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/bruce/programs/apitable/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)

```
Maybe I miss something in the README? It's totally fine run with docker in Mac m1. maybe the local mode is not supported but the error just say that `canvas` resource url is 404...

**Comment by cymqqqq** [comment]
Hi, I see your node version 20.5.0 here, right? Can U try node 16.15 again? :)

**Comment by seventhse** [comment]
I encountered the same problem. I found that the reason for the issue is that node-canvas does not support the Apple M1 chip. The solution was provided in the last comment of the [issue](https://github.com/Automattic/node-canvas/issues/2149).

**Comment by mr-kelly** [comment]
Since our community members have provided the solutions regarding the `canvas` package compatibility with Apple M1 chips (such as downgrading the Node.js version to v16.15), we will close this issue for now. If you still face environment setup errors, feel free to reopen it.
