### ISSUE TITLE
fix: room-server with error when run second time

### ISSUE THREAD

**Issue by liuck8080** [apitable/apitable#1220]
**Describe the bug**
Following the guide [Developer Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A), it can run the 3 serverices.

But after poweroff the machine and run again, it will show the following error:
```text
[ROOM_SERVER] Error     2023-08-16 15:37:11.503 [ClientProxy] ping room client :[198.18.0.1:3334] timeout, ping code:[ECONNABORTED] - {
  stack: [
    'Error: timeout of 1500ms exceeded\n' +
      '    at createError (/data/projects/apitable/apitable/node_modules/@nestjs/axios/node_modules/axios/lib/core/createError.js:16:15)\n' +
      '    at RedirectableRequest.handleRequestTimeout (/data/projects/apitable/apitable/node_modules/@nestjs/axios/node_modules/axios/lib/adapters/http.js:328:16)\n' +
      '    at RedirectableRequest.emit (node:events:527:28)\n' +
      '    at RedirectableRequest.emit (node:domain:475:12)\n' +
      '    at Timeout.<anonymous> (/data/projects/apitable/apitable/node_modules/follow-redirects/index.js:164:12)\n' +
      '    at listOnTimeout (node:internal/timers:559:17)\n' +
      '    at processTimers (node:internal/timers:502:7)'
  ]
}
[ROOM_SERVER] Info      2023-08-16 15:37:11.504 [ClientProxy] Check Room Address:「198.18.0.1:3334」. Status:offline. Offline times: 2 - {}
[ROOM_SERVER] Info      2023-08-16 15:37:11.504 [ClientProxy] Available IP Pools：172.18.0.1:3334 - {}
```

**To Reproduce**
1. Following the guide [Developer Quick Start](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A), it can run the 3 serverices.
2. Power the machine directly, without kill each server first.
3. make dataenv; make run backend-server; make run room-server

**Expected behavior**
A clean console output without error

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 22.04.3 LTS
 - zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

**Additional context**

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue
@zoe-icu Could you please take a look and assist me? Thank you.

**Comment by mr-kelly** [comment]
Thank you for providing the detailed logs. A sudden power-off or dirty shutdown often leaves orphaned background processes (like Node.js or Java processes) that continue to bind to ports, causing network conflicts or timeout errors (`ECONNABORTED`) when `room-server` tries to reconnect to the internal gRPC client after a restart.

To resolve this, please manually clean up the orphaned processes by running `pkill -f node` and `pkill -f java`, or restart your Docker containers entirely using `docker compose down -v` before running `make run` again. We will close this issue for now. Feel free to reopen it if cleaning the processes doesn't solve the problem.
