### ISSUE TITLE
fix: M1上运行 room-server 报错，前端 websocket 无法连接

### ISSUE THREAD

**Issue by tcmonster** [apitable/apitable#1268]
**描述Bug**
在 M1 电脑 docker 环境运行不了

**重现步骤**
重现行为的步骤：
1. room-server 报错反复重启
2. backend-server 报错连不上 room-server:3002
3. 前端报 websocket 错误

**期望行为**
适配 arm64 电脑

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by tcmonster** [comment]
room-server log:

2023-09-06T20:26:11: PM2 log: Launching in no daemon mode
2023-09-06T20:26:11: PM2 log: App [nest:0] starting in -cluster mode-
2023-09-06T20:26:11: PM2 log: App [nest:0] online
2023-09-06T20:26:11: PM2 log: App [nest:1] starting in -cluster mode-
2023-09-06T20:26:11: PM2 log: App [nest:1] online
2023-09-06T20:26:11: PM2 log: App [nest:2] starting in -cluster mode-
2023-09-06T20:26:11: PM2 log: App [nest:2] online
2023-09-06T20:26:11: PM2 log: App [nest:3] starting in -cluster mode-
2023-09-06T20:26:11: PM2 log: App [nest:3] online
No reducer provided for key "hooks"
No reducer provided for key "billing"
Initialized snowflake: machine ID: 0x1f9
No reducer provided for key "hooks"
No reducer provided for key "billing"
No reducer provided for key "hooks"
No reducer provided for key "billing"
Initialized snowflake: machine ID: 0x1f9
No reducer provided for key "hooks"
No reducer provided for key "billing"
Initialized snowflake: machine ID: 0x1f9
Initialized snowflake: machine ID: 0x1f9
Error: ENOENT: no such file or directory, open '/app/packages/room-server/dist/shared/helpers/list.lock.lua'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/app/packages/room-server/src/shared/helpers/redis.lock.ts:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/packages/room-server/src/database/ot/services/ot.service.ts:63:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
2023-09-06T20:26:13: PM2 log: App name:nest id:0 disconnected
2023-09-06T20:26:13: PM2 log: App [nest:0] exited with code [0] via signal [SIGINT]
2023-09-06T20:26:13: PM2 log: App [nest:0] will restart in 100ms
Error: ENOENT: no such file or directory, open '/app/packages/room-server/dist/shared/helpers/list.lock.lua'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/app/packages/room-server/src/shared/helpers/redis.lock.ts:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/packages/room-server/src/database/ot/services/ot.service.ts:63:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
2023-09-06T20:26:13: PM2 log: App name:nest id:3 disconnected
2023-09-06T20:26:13: PM2 log: App [nest:3] exited with code [0] via signal [SIGINT]
2023-09-06T20:26:13: PM2 log: App [nest:3] will restart in 100ms
Error: ENOENT: no such file or directory, open '/app/packages/room-server/dist/shared/helpers/list.lock.lua'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/app/packages/room-server/src/shared/helpers/redis.lock.ts:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/packages/room-server/src/database/ot/services/ot.service.ts:63:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
2023-09-06T20:26:13: PM2 log: App name:nest id:2 disconnected
2023-09-06T20:26:13: PM2 log: App [nest:2] exited with code [0] via signal [SIGINT]
2023-09-06T20:26:13: PM2 log: App [nest:2] will restart in 100ms
2023-09-06T20:26:13: PM2 log: App [nest:0] starting in -cluster mode-
Error: ENOENT: no such file or directory, open '/app/packages/room-server/dist/shared/helpers/list.lock.lua'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (/app/packages/room-server/src/shared/helpers/redis.lock.ts:24:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at Module.Hook._require.Module.require (/app/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/packages/room-server/src/database/ot/services/ot.service.ts:63:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)

**Comment by pengjin123** [comment]
Thank you for your feedback ,we have assigned relevant colleagues to follow up this issue
@zoe-icu Could you please help me take a look? Thank you

**Comment by kennedy8312** [comment]
I am seeing this problem on M1pro, OS:12.6.86. Is it possible to have a temporary workaround while waiting for the future solution?

**Comment by kennedy8312** [comment]
google 检索相关错误基本提示与 node,pnpm相关，遂怀疑是Apple Silcon相关问题，google 调研无果。官方 Issue 检索发现类似问题尚在 open 状态，官方 2022.12 开始提供 arm 镜像尝试，初期经历 init-db, backend-server等各种无法启动的问题，现已解决，当前问题由于“the nextjs assets copying procedure breaks in slow arm64 image build due to qemu emulation.”导致，修复方法手动从 GitHub下载缺失文件，导入 docker image 重启或者修改docker-compose.yaml使image 与本地文件绑定。

**Comment by mr-kelly** [comment]
Thank you for your feedback. Running APITable natively on ARM64 architectures (like Apple Silicon M1/M2) has historically faced compatibility issues with certain base images and the `room-server`. We are continuously working on improving ARM64 support and have recorded this to track the native Apple Silicon build progress.

---

感谢您的反馈。在 ARM64 架构（如 Apple Silicon M1/M2）上原生运行 APITable，历史上一直面临着某些基础镜像和 `room-server` 的兼容性问题。我们正在不断努力改善对 ARM64 的支持，并已将其记录下来以跟踪原生 Apple Silicon 构建的进度。
