### ISSUE TITLE
Development environment  and the page shows "Request failed with status code 504"

### ISSUE THREAD

**Issue by 17x** [apitable/apitable#1287]
**Describe the bug**
Error: Page gives me 'Server Error Request failed with status code 504' and chrome Devtool console gives me something like 'next-dev.js:20 No reducer provided for key "hooks"'

**To Reproduce**
1. follow [development environment](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A)
2. finish all operations before then run ```make run # enter 3```
3. open that link shown in the terminal

Similar with this [issue](https://github.com/apitable/apitable/issues/1268)

**Expected behavior**
ApiTable interface can display normally

**Screenshots**
<img width="1437" alt="Screenshot 2023-09-08 at 16 42 52" src="https://github.com/apitable/apitable/assets/17699833/b6968f1b-ee68-48a8-8225-f7559e0365a7">

**Desktop (please complete the following information):**
Macbook Air m1  (2020)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
 
**Additional context**
Actually i came from [AITable Simple Developers Test](https://aitable.ai/share/shrDNBDeVlLvB1eFDMWhl/fom4DPpt6TnHaE9XnA)

**Comment by pengjin123** [comment]
@17x Could you please check if there are any error messages on your bank server and web server services?

**Comment by hockor** [comment]
同样的问题 

环境：2019 intel 芯片 macbook pro 16


java 报错如下：：


Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-09-19 15:07:57.659 ERROR [service-api,,] 50627 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.apitable.Application.main(Application.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:275)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.start(RedisMessageListenerContainer.java:249)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 20 common frames omitted
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:292)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:515)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$Subscriber.initialize(RedisMessageListenerContainer.java:1186)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.doSubscribe(RedisMessageListenerContainer.java:318)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:295)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:265)
	... 22 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:84)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:377)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:15)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:283)
	... 27 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
	at redis.clients.jedis.Protocol.processError(Protocol.java:142)
	at redis.clients.jedis.Protocol.process(Protocol.java:176)
	at redis.clients.jedis.Protocol.read(Protocol.java:230)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270)
	at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2714)
	at redis.clients.jedis.BinaryJedis.initializeFromClientConfig(BinaryJedis.java:99)
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:297)
	at redis.clients.jedis.Jedis.<init>(Jedis.java:169)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:177)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:75)
	... 30 common frames omitted

**Comment by hockor** [comment]
<img width="1527" alt="image" src="https://github.com/apitable/apitable/assets/6330861/6088bb46-877f-4238-9e78-4cbf12f48ba9">

**Comment by hockor** [comment]
我晕死，最后我们自己搞定了，是 yml 配置的问题

**Comment by zhaopan-pan** [comment]
> 我晕死，最后我们自己搞定了，是 yml 配置的问题

具体什么配置呢？

**Comment by hockor** [comment]
> > 我晕死，最后我们自己搞定了，是 yml 配置的问题
> 
> 具体什么配置呢？

修改的地方
在执行 make dataenv之前先改下代码

修改一
文件路径：docker-compose.yaml:153
修改内容
注释掉 153 行和 154 行内容

``` 
  redis:   
    container_name: redis   
    image: ${IMAGE_REDIS}   
    pull_policy: ${IMAGE_PULL_POLICY:-if_not_present}

    restart: always   
    command:   
      [
          "redis-server",   
          "--appendonly",   
          "yes",   
          # "--requirepass",   
          # "${REDIS_PASSWORD}",   
      ]

```
修改二
文件路径： backend-server/application/src/main/resources/application.yml
修改内容
注释掉 23 行和 24 行

```
# Redis
  redis:
    host: ${REDIS_HOST:127.0.0.1}
#    username: ${REDIS_USERNAME:}
#    password: ${REDIS_PASSWORD:apitable@com}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB:0}
    timeout: ${REDIS_TIMEOUT:30000}
    ssl: ${REDIS_SSL_ENABLED:false}
```
修改完毕以后再执行  make dateenv，以及后续的  make run

**Comment by zhaxie** [comment]
> docker-compose.yam

没用，还是504

**Comment by mr-kelly** [comment]
Thank you for the report and to everyone who shared their debugging logs and workarounds. The 504 errors in the local development environment are often tied to backend initialization failures, specifically regarding Redis connection authentication or Docker compose configurations. We have recorded this environment setup issue and will work on streamlining the developer quick-start configuration.

---

感谢您的反馈，也感谢分享调试日志和解决办法的各位。本地开发环境中的 504 错误通常与后端初始化失败有关，特别是涉及到 Redis 连接身份验证或 Docker compose 配置问题。我们已经记录了这个环境搭建问题，并将努力优化开发者快速启动配置。
