### ISSUE TITLE
make run 2 failed due to permission

### ISSUE THREAD

**Issue by wayou** [apitable/apitable#1304]
following steps in the [guide](https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/developer-quick-start-zofpBpXg9A)

```
make run 2
```

failed with the following log:

```
[Nest] 88657  - 09/12/2023, 10:27:56 AM   ERROR [TypeOrmModule] Unable to connect to the database. Message: Access denied for user 'root'@'localhost' (using password: YES). Retrying (9)...
Error: Access denied for user 'root'@'localhost' (using password: YES)
    at Packet.asError (/Users/xxx/work/github/apitable/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/Users/xxx/work/github/apitable/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/xxx/work/github/apitable/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/xxx/work/github/apitable/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/xxx/work/github/apitable/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/xxx/work/github/apitable/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by wayou** [comment]
remove yarn.lock and re-install do resolve the problem, but others may still get the same error.

**Comment by ChambersChan** [comment]
There is a high probability that there is a problem with the steps before starting the service. MySQL is not healthy or is not running.
