### ISSUE TITLE
fix: uploading pdf file, using api, 500-internel error

### ISSUE THREAD

**Issue by cwmine** [apitable/apitable#1496]
**Describe the bug**
I test the attachment uploading using API,  no wrong for hours. 
Suddenly, no codes changed, upload the same file ,return 500-internal server error 

**To Reproduce**
using API to upload 3MB pdf file

**Expected behavior**
backend log
```
long to templates
2023-12-01 01:02:55.810  INFO [service-api,bfe67461a4179f99b03f665f97d3b3ac,1471d3fda6f4e4d7] 1 --- [nio-8081-exec-9] c.a.s.service.impl.SpaceRoleServiceImpl  : Queries all space administrators who have workben
ch permission，including the main admin.
2023-12-01 01:02:55.811  INFO [service-api,bfe67461a4179f99b03f665f97d3b3ac,1471d3fda6f4e4d7] 1 --- [nio-8081-exec-9] c.a.space.service.impl.SpaceServiceImpl  : gets space global properties，spaceId:spc2ShdNUcb
Sn
2023-12-01 01:02:55.813  INFO [service-api,bfe67461a4179f99b03f665f97d3b3ac,1471d3fda6f4e4d7] 1 --- [nio-8081-exec-9] c.a.w.service.impl.FieldRoleServiceImpl  : The member [1698988213869858817] obtains the fiel
d permission of the node [dstEoqM57P47H4KHPY] and shares the ID: [null]
2023-12-01 01:02:55.821  INFO [service-api,1280023cf870bbc5cb4f7efa6ad10fc6,05835d70de9ace5e] 1 --- [nio-8081-exec-7] c.a.space.service.impl.SpaceServiceImpl  : Obtain the capacity information of the space
2023-12-01 01:02:55.830  INFO [service-api,755fb62bf9233bd8db98f91b2a443761,0bea7762907374c9] 1 --- [nio-8081-exec-8] c.a.asset.service.impl.AssetServiceImpl  : upload resources in the space
2023-12-01 01:02:55.833  INFO [service-api,755fb62bf9233bd8db98f91b2a443761,0bea7762907374c9] 1 --- [nio-8081-exec-8] c.a.asset.service.impl.AssetServiceImpl  : PDF to generate pictures
2023-12-01 01:02:55.895 ERROR [service-api,755fb62bf9233bd8db98f91b2a443761,0bea7762907374c9] 1 --- [nio-8081-exec-8] com.apitable.shared.util.PdfToImageUtil  : unable to load pdf

java.awt.image.RasterFormatException: (x + width) is outside raster
        at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:467)
        at sun.awt.image.IntegerInterleavedRaster.createChild(IntegerInterleavedRaster.java:514)
        at sun.java2d.pipe.GeneralCompositePipe.renderPathTile(GeneralCompositePipe.java:106)
        at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:202)
        at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:150)
        at sun.java2d.pipe.AAShapePipe.fill(AAShapePipe.java:83)
        at sun.java2d.pipe.PixelToParallelogramConverter.fill(PixelToParallelogramConverter.java:164)

      2023-12-01 01:02:55.900 ERROR [service-api,755fb62bf9233bd8db98f91b2a443761,cc3aa6b680043e0a] 1 --- [nio-8081-exec-8] c.a.s.component.GlobalExceptionHandler   : internal service exception:

org.springframework.jdbc.BadSqlGrammarException:
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHER
E id=1730264168116842498  AND is_deleted=0' at line 1
### The error may exist in com/apitable/asset/mapper/AssetMapper.java (best guess)
### The error may involve com.apitable.asset.mapper.AssetMapper.updateById-Inline
### The error occurred while setting parameters
### SQL: UPDATE apitable_asset    WHERE id=?  AND is_deleted=0
### Cause: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=1730264168116842498
AND is_deleted=0' at line 1
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near
'WHERE id=1730264168116842498  AND is_deleted=0' at line 1
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
        at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:91)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441)
        at com.sun.proxy.$Proxy173.update(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.update(SqlSessionTemplate.java:288)
        at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:64)
        at com.baomidou.mybatisplus.core.override.MybatisMapperProxy$PlainMethodInvoker.invoke(MybatisMapperProxy.java:148)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id=1730264168116842498  AND is_deleted=0' at line 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at com.p6spy.engine.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:362)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
        at sun.reflect.GeneratedMethodAccessor595.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:64)
        at com.sun.proxy.$Proxy343.update(Unknown Source)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
        at sun.reflect.GeneratedMethodAccessor594.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
        at com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor.intercept(MybatisPlusInterceptor.java:106)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
        at com.sun.proxy.$Proxy342.update(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:194)
        at sun.reflect.GeneratedMethodAccessor661.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
        ... 156 common frames omitted



```

**Screenshots**
API invoke

**Additional context**

docker self-hosted latest version

**Comment by cwmine** [comment]
@ChambersChan  why close the issue?

**Comment by ChambersChan** [comment]
@cwmine oo. The PR merge automatically closes the associated issue. 
The fix will take effect in next Monday night's version.
