### ISSUE TITLE
Docker compose upgrade fail 

### ISSUE THREAD

**Issue by curtishall** [apitable/apitable#1536]
Following the instructions online (https://apitable.getoutline.com/s/751b142b-866f-4174-a5f1-a2975f85ad41/doc/troubleshooting-ogBPfk3YTW#h-how-to-upgrade-to-the-newest-release-version) I am unable to successfully start docker compose after downloading the latest release.

Eventually after starting I get "service "init-db" didn't complete successfully: exit 1"

docker compose logs init-db show the following:

```
Unexpected error running Liquibase: Could not acquire change log lock.  Currently locked by d380e8ac9ef1 (172.18.0.8) since 6/24/23, 3:13 AM
```

How do I remove this lock?

```
apitable-init-db-1  | Starting Liquibase at 03:22:59 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
apitable-init-db-1  | Liquibase Version: 4.21.1
apitable-init-db-1  | Liquibase Open Source 4.21.1 by Liquibase
apitable-init-db-1  | [2023-12-21 03:28:00] SEVERE [liquibase.integration] Could not acquire change log lock.  Currently locked by d380e8ac9ef1 (172.18.0.8) since 6/24/23, 3:13 AM
apitable-init-db-1  | liquibase.exception.CommandExecutionException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by d380e8ac9ef1 (172.18.0.8) since 6/24/23, 3:13 AM
apitable-init-db-1  |   at liquibase.command.CommandScope.execute(CommandScope.java:235)
apitable-init-db-1  |   at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
apitable-init-db-1  |   at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
apitable-init-db-1  |   at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
apitable-init-db-1  |   at picocli.CommandLine.access$1500(CommandLine.java:148)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
apitable-init-db-1  |   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
apitable-init-db-1  |   at picocli.CommandLine.execute(CommandLine.java:2170)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$2(LiquibaseCommandLine.java:383)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:203)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:179)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:203)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:179)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:93)
apitable-init-db-1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apitable-init-db-1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
apitable-init-db-1  |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
apitable-init-db-1  |   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
apitable-init-db-1  | Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by d380e8ac9ef1 (172.18.0.8) since 6/24/23, 3:13 AM
apitable-init-db-1  |   at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:277)
apitable-init-db-1  |   at liquibase.command.core.helpers.LockServiceCommandStep.run(LockServiceCommandStep.java:38)
apitable-init-db-1  |   at liquibase.command.CommandScope.execute(CommandScope.java:212)
apitable-init-db-1  |   ... 23 more
apitable-init-db-1  | 
apitable-init-db-1  | 
apitable-init-db-1  | Unexpected error running Liquibase: Could not acquire change log lock.  Currently locked by d380e8ac9ef1 (172.18.0.8) since 6/24/23, 3:13 AM
apitable-init-db-1  | 
apitable-init-db-1  | liquibase.exception.CommandExecutionException: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by d380e8ac9ef1 (172.18.0.8) since 6/24/23, 3:13 AM
apitable-init-db-1  |   at liquibase.command.CommandScope.execute(CommandScope.java:235)
apitable-init-db-1  |   at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
apitable-init-db-1  |   at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
apitable-init-db-1  |   at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
apitable-init-db-1  |   at picocli.CommandLine.access$1500(CommandLine.java:148)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
apitable-init-db-1  |   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
apitable-init-db-1  |   at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
apitable-init-db-1  |   at picocli.CommandLine.execute(CommandLine.java:2170)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$2(LiquibaseCommandLine.java:383)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:203)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:179)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:203)
apitable-init-db-1  |   at liquibase.Scope.child(Scope.java:179)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:93)
apitable-init-db-1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
apitable-init-db-1  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
apitable-init-db-1  |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
apitable-init-db-1  |   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
apitable-init-db-1  |   at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
apitable-init-db-1  | Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by d380e8ac9ef1 (172.18.0.8) since 6/24/23, 3:13 AM
apitable-init-db-1  |   at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:277)
apitable-init-db-1  |   at liquibase.command.core.helpers.LockServiceCommandStep.run(LockServiceCommandStep.java:38)
apitable-init-db-1  |   at liquibase.command.CommandScope.execute(CommandScope.java:212)
apitable-init-db-1  |   ... 23 more
```

```
root@apitable:/home/curt/apps/apitable# curl -fLo docker-compose.tar.gz 'https://github.com/apitable/apitable.github.io/releases/latest/download/docker-compose.tar.gz'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2568  100  2568    0     0   5594      0 --:--:-- --:--:-- --:--:--  5594
root@apitable:/home/curt/apps/apitable# tar -xvzf docker-compose.tar.gz
.env
docker-compose.yaml                                                                    sudo docker compose pullt/apps/apitable# diff docker-compose.yaml docker-compose.yaml.bac.yaml.backup^C
root@apitable:/home/curt/apps/apitable# docker compose up -d
[+] Running 12/12
 ✔ web-server Pulled                                                       0.6s 
 ✔ redis Pulled                                                            0.6s 
 ✔ backend-server Pulled                                                   0.6s 
 ✔ room-server Pulled                                                      0.6s 
 ✔ rabbitmq Pulled                                                         0.6s 
 ✔ minio Pulled                                                            0.6s 
 ✔ databus-server Pulled                                                   0.6s 
 ✔ imageproxy-server Pulled                                                0.7s 
 ✔ init-db Pulled                                                          0.6s 
 ✔ gateway Pulled                                                          0.6s 
 ✔ mysql Pulled                                                            0.6s 
 ✔ init-appdata Pulled                                                     0.6s 
[+] Running 9/9
 ✔ Container apitable-imageproxy-server-1  Running                         0.0s 
 ✔ Container rabbitmq                      Running                         0.0s 
 ✔ Container apitable-web-server-1         Running                         0.0s 
 ✔ Container minio                         Running                         0.0s 
 ✔ Container mysql                         Healthy                         0.0s 
 ✔ Container redis                         Running                         0.0s 
 ✘ Container apitable-init-db-1            service "init-db" didn't complete successfully: exit 10.0s pitable-room-server-1       
 ✔ Container apitable-room-server-1        Running                         0.0s 
 ✔ Container apitable-databus-server-1     Running                         0.0s 
service "init-db" didn't complete successfully: exit 1

**Comment by curtishall** [comment]
Seems similar to however it shows fixed (https://github.com/apitable/apitable/issues/819)?

**Comment by curtishall** [comment]
I was using apitable from an old directory...this is not a bug....user error.
