### ISSUE TITLE
Does deploying the all-in-one image demo require using sudo?

### ISSUE THREAD

**Issue by wojing** [apitable/apitable#1539]
I don't have sudo privileges, so I'm using Docker without sudo. Here is the command I'm using:
`docker run -d -v ${PWD}/.data:/apitable -p 6780:80 --name apitable apitable/all-in-one:latest`

Unfortunately, this command is not working and I'm encountering errors.
`    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/v1/client/info?spaceId=',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'backend-server',
      port: '8081',
      nativeProtocols: [Object],
      pathname: '/api/v1/client/info',
      search: '?spaceId='
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/v1/client/info?spaceId= HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: backend-server:8081\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/client/info?spaceId=',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'backend-server',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://backend-server:8081/api/v1/client/info?spaceId=',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error`

**Comment by networkhermit** [comment]
Quote from README:

> Depending on your environment, you may need to wait several minutes for all the services to start. This image is amd64 (x86_64) only, you may encounter pretty bad performance on arm64 or apple silicon.

**Comment by wojing** [comment]
I have been waiting for one day, and it is still going like that.

**Comment by networkhermit** [comment]
> I have been waiting for one day, and it is still going like that.

You can troubleshoot the internal status by running the following commands in the all-in-one container:

```bash
pm2 status
pm2 logs backend-server
```

**Comment by wojing** [comment]
> > I have been waiting for one day, and it is still going like that.
> 
> You can troubleshoot the internal status by running the following commands in the all-in-one container:
> 
> ```shell
> pm2 status
> pm2 logs backend-server
> ```

[root@35a6df98adc5 /]# pm2 logs backend-server
[TAILING] Tailing last 15 lines for [backend-server] process (change the value with --lines option)


^C
[root@35a6df98adc5 /]# pm2 status
┌────┬──────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name                 │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 5  │ backend-server       │ default     │ N/A     │ fork    │ 29831    │ 2m     │ 289  │ online    │ 0%       │ 1.7mb    │ root     │ disabled │
│ 6  │ databus-server       │ default     │ N/A     │ fork    │ 319      │ 24h    │ 4    │ online    │ 0%       │ 80.2mb   │ root     │ disabled │
│ 2  │ gateway              │ default     │ N/A     │ fork    │ 37       │ 24h    │ 0    │ online    │ 0%       │ 1.7mb    │ root     │ disabled │
│ 9  │ imageproxy-server    │ default     │ N/A     │ fork    │ 160      │ 24h    │ 0    │ online    │ 0%       │ 19.3mb   │ root     │ disabled │
│ 0  │ minio                │ default     │ N/A     │ fork    │ 20       │ 24h    │ 0    │ online    │ 0%       │ 113.6mb  │ root     │ disabled │
│ 1  │ mysql                │ default     │ N/A     │ fork    │ 26       │ 24h    │ 0    │ online    │ 0%       │ 435.2mb  │ root     │ disabled │
│ 3  │ rabbitmq             │ default     │ N/A     │ fork    │ 39       │ 24h    │ 0    │ online    │ 0%       │ 1.8mb    │ root     │ disabled │
│ 4  │ redis                │ default     │ N/A     │ fork    │ 51       │ 24h    │ 0    │ online    │ 0%       │ 10.2mb   │ root     │ disabled │
│ 7  │ room-server          │ default     │ 1.7.0   │ fork    │ 87       │ 24h    │ 0    │ online    │ 0%       │ 191.2mb  │ root     │ disabled │
│ 8  │ web-server           │ default     │ N/A     │ fork    │ 152      │ 24h    │ 0    │ online    │ 0%       │ 274.5mb  │ root     │ disabled │

The uptime  looks like  backend_server will reboot always.

**Comment by lmtr0** [comment]
It seems migrations are failing:
```
5|backend-server  | ####################################################
5|backend-server  | ##   _     _             _ _                      ##
5|backend-server  | ##  | |   (_)           (_) |                     ##
5|backend-server  | ##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
5|backend-server  | ##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
5|backend-server  | ##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
5|backend-server  | ##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
5|backend-server  | ##              | |                               ##
5|backend-server  | ##              |_|                               ##
5|backend-server  | ##                                                ##
5|backend-server  | ##  Get documentation at docs.liquibase.com       ##
5|backend-server  | ##  Get certified courses at learn.liquibase.com  ##
5|backend-server  | ##  Free schema change activity reports at        ##
5|backend-server  | ##      https://hub.liquibase.com                 ##
5|backend-server  | ##                                                ##
5|backend-server  | ####################################################
5|backend-server  | Starting Liquibase at 15:33:59 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
5|backend-server  | Liquibase Version: 4.21.1
5|backend-server  | Liquibase Open Source 4.21.1 by Liquibase
5|backend-server  | Liquibase command 'clearChecksums' was executed successfully.
5|backend-server  | ####################################################
5|backend-server  | ##   _     _             _ _                      ##
5|backend-server  | ##  | |   (_)           (_) |                     ##
5|backend-server  | ##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
5|backend-server  | ##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
5|backend-server  | ##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
5|backend-server  | ##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
5|backend-server  | ##              | |                               ##
5|backend-server  | ##              |_|                               ##
5|backend-server  | ##                                                ##
5|backend-server  | ##  Get documentation at docs.liquibase.com       ##
5|backend-server  | ##  Get certified courses at learn.liquibase.com  ##
5|backend-server  | ##  Free schema change activity reports at        ##
5|backend-server  | ##      https://hub.liquibase.com                 ##
5|backend-server  | ##                                                ##
5|backend-server  | ####################################################
5|backend-server  | Starting Liquibase at 15:34:00 (version 4.21.1 #9070 built at 2023-04-13 20:56+0000)
5|backend-server  | Liquibase Version: 4.21.1
5|backend-server  | Liquibase Open Source 4.21.1 by Liquibase
5|backend-server  | Running Changeset: db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng
5|backend-server  | [2025-06-13 15:34:04] SEVERE [liquibase.changelog] ChangeSet db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng encountered an exception.
5|backend-server  | [2025-06-13 15:34:04] SEVERE [liquibase.integration] Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  | liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.command.CommandScope.execute(CommandScope.java:235)
5|backend-server  |     at com.datical.liquibase.ext.command.ProUpdateCommandStep.run(Unknown Source)
5|backend-server  |     at liquibase.command.CommandScope.execute(CommandScope.java:212)
5|backend-server  |     at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
5|backend-server  |     at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
5|backend-server  |     at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
5|backend-server  |     at picocli.CommandLine.access$1500(CommandLine.java:148)
5|backend-server  |     at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
5|backend-server  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
5|backend-server  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
5|backend-server  |     at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
5|backend-server  |     at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
5|backend-server  |     at picocli.CommandLine.execute(CommandLine.java:2170)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$2(LiquibaseCommandLine.java:383)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:179)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:179)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:93)
5|backend-server  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
5|backend-server  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
5|backend-server  |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
5|backend-server  |     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
5|backend-server  | Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:123)
5|backend-server  |     at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:102)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:99)
5|backend-server  |     ... 25 more
5|backend-server  | Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.changelog.ChangeSet.execute(ChangeSet.java:761)
5|backend-server  |     at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:61)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:111)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.Scope.child(Scope.java:260)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.Scope.child(Scope.java:260)
5|backend-server  |     at liquibase.Scope.child(Scope.java:264)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:68)
5|backend-server  |     ... 31 more
5|backend-server  | Caused by: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:445)
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
5|backend-server  |     at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1287)
5|backend-server  |     at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1269)
5|backend-server  |     at liquibase.changelog.ChangeSet.execute(ChangeSet.java:718)
5|backend-server  |     ... 51 more
5|backend-server  | Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1
5|backend-server  |     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
5|backend-server  |     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
5|backend-server  |     at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
5|backend-server  |     at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:441)
5|backend-server  |     ... 56 more
5|backend-server  | Unexpected error running Liquibase: Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  | liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.command.CommandScope.execute(CommandScope.java:235)
5|backend-server  |     at com.datical.liquibase.ext.command.ProUpdateCommandStep.run(Unknown Source)
5|backend-server  |     at liquibase.command.CommandScope.execute(CommandScope.java:212)
5|backend-server  |     at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:55)
5|backend-server  |     at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:24)
5|backend-server  |     at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
5|backend-server  |     at picocli.CommandLine.access$1500(CommandLine.java:148)
5|backend-server  |     at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
5|backend-server  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
5|backend-server  |     at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
5|backend-server  |     at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
5|backend-server  |     at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
5|backend-server  |     at picocli.CommandLine.execute(CommandLine.java:2170)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.lambda$null$2(LiquibaseCommandLine.java:383)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:179)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$3(LiquibaseCommandLine.java:358)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:179)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:356)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:93)
5|backend-server  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
5|backend-server  |     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
5|backend-server  |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
5|backend-server  |     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
5|backend-server  |     at liquibase.integration.commandline.LiquibaseLauncher.main(LiquibaseLauncher.java:107)
5|backend-server  | Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:123)
5|backend-server  |     at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:102)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:99)
5|backend-server  |     ... 25 more
5|backend-server  | Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset db/changelog/0.3/20200407_changeset.xml::V0.3-20200407-002::ZoeZheng:
5|backend-server  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.changelog.ChangeSet.execute(ChangeSet.java:761)
5|backend-server  |     at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:61)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:111)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.Scope.child(Scope.java:260)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
5|backend-server  |     at liquibase.Scope.lambda$child$0(Scope.java:194)
5|backend-server  |     at liquibase.Scope.child(Scope.java:203)
5|backend-server  |     at liquibase.Scope.child(Scope.java:193)
5|backend-server  |     at liquibase.Scope.child(Scope.java:172)
5|backend-server  |     at liquibase.Scope.child(Scope.java:260)
5|backend-server  |     at liquibase.Scope.child(Scope.java:264)
5|backend-server  |     at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:68)
5|backend-server  |     ... 31 more
5|backend-server  | Caused by: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1 [Failed SQL: (1064) ALTER TABLE apitable_     -DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varchar(255) not null comment 'Version Description']
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:445)
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77)
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160)
5|backend-server  |     at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1287)
5|backend-server  |     at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1269)
5|backend-server  |     at liquibase.changelog.ChangeSet.execute(ChangeSet.java:718)
5|backend-server  |     ... 51 more
5|backend-server  | Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-DDB_ENGINE=mysqlclient_release_version change  `describe`  `description`  varch' at line 1
5|backend-server  |     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
5|backend-server  |     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
5|backend-server  |     at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
5|backend-server  |     at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
5|backend-server  |     at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:441)
5|backend-server  |     ... 56 more
```

the backend server has restarted 48 times

**Comment by mr-kelly** [comment]
Using Docker without `sudo` (e.g., via the docker group) is generally fine. The `500 Internal Server Error` and the underlying `SQLSyntaxErrorException` from liquibase in your logs suggest that there might be a permission issue with the mapped `.data` volume or corrupted leftover database files. Please ensure your current user has write permissions to `/home/kelly/Documents/projects/apitable/.data`, or try deleting the `.data` folder and running the container again for a fresh initialization.
