### ISSUE TITLE
feat: add support for aliyun oss

### ISSUE THREAD

**Issue by Jinkeycode** [apitable/apitable#560]
I have an idea for this project.

## Why? 
Most of developer in chinese use aliyun

Now, when we implement oss config，it raise error.

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teamServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceInviteLinkServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assetServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assetAuditServiceImpl': Unsatisfied dependency expressed through field 'ossTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ossClientTemplate' defined in class path resource [com/apitable/starter/oss/autoconfigure/OssAutoConfiguration.class]: Unsatisfied dependency expressed through method 'ossClientTemplate' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.apitable.starter.oss.core.OssClientRequestFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
1-backend-server-1     |        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
1-backend-server-1     |        ... 232 common frames omitted
1-backend-server-1     | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceInviteLinkServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assetServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assetAuditServiceImpl': Unsatisfied dependency expressed through field 'ossTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ossClientTemplate' defined in class path resource [com/apitable/starter/oss/autoconfigure/OssAutoConfiguration.class]: Unsatisfied dependency expressed through method 'ossClientTemplate' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.apitable.starter.oss.core.OssClientRequestFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
1-backend-server-1     |        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
1-backend-server-1     |        ... 248 common frames omitted
1-backend-server-1     | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assetServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assetAuditServiceImpl': Unsatisfied dependency expressed through field 'ossTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ossClientTemplate' defined in class path resource [com/apitable/starter/oss/autoconfigure/OssAutoConfiguration.class]: Unsatisfied dependency expressed through method 'ossClientTemplate' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.apitable.starter.oss.core.OssClientRequestFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations
```

**Comment by mr-kelly** [comment]
> I have an idea for this project.
> 
> ## Why?
> Most of developer in chinese use aliyun
> 
> Now, when we implement oss config，it raise error.
> 
> ```
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teamServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceInviteLinkServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assetServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assetAuditServiceImpl': Unsatisfied dependency expressed through field 'ossTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ossClientTemplate' defined in class path resource [com/apitable/starter/oss/autoconfigure/OssAutoConfiguration.class]: Unsatisfied dependency expressed through method 'ossClientTemplate' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.apitable.starter.oss.core.OssClientRequestFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
> 1-backend-server-1     |        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
> 1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
> 1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
> 1-backend-server-1     |        ... 232 common frames omitted
> 1-backend-server-1     | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceInviteLinkServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assetServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assetAuditServiceImpl': Unsatisfied dependency expressed through field 'ossTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ossClientTemplate' defined in class path resource [com/apitable/starter/oss/autoconfigure/OssAutoConfiguration.class]: Unsatisfied dependency expressed through method 'ossClientTemplate' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.apitable.starter.oss.core.OssClientRequestFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:332)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
> 1-backend-server-1     |        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
> 1-backend-server-1     |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:544)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:520)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:673)
> 1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:228)
> 1-backend-server-1     |        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
> 1-backend-server-1     |        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:329)
> 1-backend-server-1     |        ... 248 common frames omitted
> 1-backend-server-1     | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spaceServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'assetServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'assetAuditServiceImpl': Unsatisfied dependency expressed through field 'ossTemplate'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ossClientTemplate' defined in class path resource [com/apitable/starter/oss/autoconfigure/OssAutoConfiguration.class]: Unsatisfied dependency expressed through method 'ossClientTemplate' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.apitable.starter.oss.core.OssClientRequestFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations
> ```

What does this have to do with Aliyun OSS?

**Comment by mr-kelly** [comment]
What is this problem? Please describe it in detail.

There is no relevance to Aliyun OSS in your issue description.

**Comment by Jinkeycode** [comment]
Your developer let me open this issue, why you close this issue

**Comment by networkhermit** [comment]
@Jinkeycode 
Reopened as it is mistaken for irrelevant issue report, acctually it is a feature request.
