### ISSUE TITLE
question: Q&A...It has been in normal use for a long time, but now it can't be opened, how to solve it? Stuck in the logo interface

### ISSUE THREAD

**Issue by wzzzzzz1111** [apitable/apitable#585]
## Any questions?
![image](https://user-images.githubusercontent.com/125652293/226177616-a891ed19-6224-4a60-97d5-794d928f689d.png)
It has been in normal use for a long time, but now it can't be opened, how to solve it? Stuck in the logo interface

**Comment by nagisakon** [comment]
Please provide more detailed error information.

**Comment by wzzzzzz1111** [comment]
![image](https://user-images.githubusercontent.com/125652293/226776934-172f4db5-dc34-47de-972f-8e01f053023a.png)

**Comment by wzzzzzz1111** [comment]
> 请提供更详细的错误信息。

![image](https://user-images.githubusercontent.com/125652293/226777021-3c408979-1859-49c3-8a87-c989b33d33a6.png)

**Comment by wzzzzzz1111** [comment]
> 请提供更详细的错误信息。

I don't look at the backend code, I can only judge from this that he is wrong

**Comment by wzzzzzz1111** [comment]
![image](https://user-images.githubusercontent.com/125652293/226793115-60266b9f-2b60-43e3-8fae-4f5f6f4664ef.png)

**Comment by wzzzzzz1111** [comment]
![image](https://user-images.githubusercontent.com/125652293/226793938-4a47e745-2b48-4565-ae8c-3e1365ec22a1.png)
![Uploading image.png…]()

**Comment by wzzzzzz1111** [comment]
![image](https://user-images.githubusercontent.com/125652293/226802822-5f89c4a5-8876-4596-8754-ee59e32aa743.png)

**Comment by nagisakon** [comment]
Looks like a problematic deployment, please check the status and logs of the back-end service.

**Comment by wzzzzzz1111** [comment]
> 看起来部署有问题，请检查后端服务的状态和日志。

2023-03-31 12:26:55.159 ERROR [service-api,,] 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'springSessionRedisMessageListenerContainer'; nested exception is org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.apitable.Application.main(Application.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.data.redis.listener.adapter.RedisListenerExecutionFailedException: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:275)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.start(RedisMessageListenerContainer.java:249)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 20 common frames omitted
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:292)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:515)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$Subscriber.initialize(RedisMessageListenerContainer.java:1186)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.doSubscribe(RedisMessageListenerContainer.java:318)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:295)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.lazyListen(RedisMessageListenerContainer.java:265)
	... 22 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:84)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:377)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:15)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:283)
	... 27 common frames omitted
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:110)
	at redis.clients.jedis.Connection.connect(Connection.java:226)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:144)
	at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:314)
	at redis.clients.jedis.BinaryJedis.initializeFromClientConfig(BinaryJedis.java:92)
	at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:297)
	at redis.clients.jedis.Jedis.<init>(Jedis.java:169)
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:177)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:75)
	... 30 common frames omitted
Caused by: java.net.UnknownHostException: redis
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:80)
	... 41 common frames omitted

**Comment by RuralDependencies** [comment]
I'm getting the same problem as of the moment. The server stopped (electricity shutdown) and now it's not restarting after reboot. It's stuck.

![image](https://user-images.githubusercontent.com/55824167/229070156-fbccab32-29db-42c0-9986-2e3200fac500.png)

**Comment by mr-kelly** [comment]
Thank you for providing the detailed logs. The `Cannot get Jedis connection` error in the Spring Boot backend confirms that the Redis container failed to start properly. As another community member experienced, sudden power outages or ungraceful shutdowns often corrupt the Redis AOF (Append-Only File) persistence data, causing Redis to crash on reboot, which in turn brings down the backend. To recover, you need to clear the corrupted Redis data volume or disable AOF in your local configuration. Since this is an environment-specific recovery issue, we will close it for now.

---

感谢您提供详细的日志。Spring Boot 后端中的 `Cannot get Jedis connection` 错误证实了 Redis 容器未能正常启动。正如另一位社区成员所经历的，突然断电或非正常关机通常会损坏 Redis AOF (Append-Only File) 持久化数据，导致 Redis 在重启时崩溃，进而导致后端服务宕机。为了恢复，您需要清理损坏的 Redis 数据卷，或在本地配置中禁用 AOF。由于这是一个特定于环境的灾难恢复问题，我们将暂时关闭它。
