### ISSUE TITLE
fix: BUG on attachments, widgets and images

### ISSUE THREAD

**Issue by ratnikov-in** [apitable/apitable#649]
**Describe the bug**

**To Reproduce**
1. Go to dashboard
2. see error

1.Add field attachment
2. Add source
3. Timeout - error

**Screenshots**
<img width="1600" alt="Снимок экрана 2023-03-27 в 21 32 25" src="https://user-images.githubusercontent.com/37483261/228034763-54fd6b7c-ca7e-43e7-966b-d9a7bb6c8285.png">
<img width="1421" alt="Снимок экрана 2023-03-27 в 21 29 43" src="https://user-images.githubusercontent.com/37483261/228034773-e5441c66-36fb-40fe-b789-742437fb6f9d.png">
<img width="403" alt="Снимок экрана 2023-03-27 в 21 29 20" src="https://user-images.githubusercontent.com/37483261/228034777-ac963b8b-555f-4da8-acf1-04408a5d58b4.png">

**Desktop (please complete the following information):**
 - Browser [chrome]

**Comment by ratnikov-in** [comment]
In logs docker
```
gateway_1            | 2023/03/28 03:36:06 [error] 7#7: *5 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.113.0, server: 127.0.0.1, request: "PUT /space/2023/03/27/bc1c6af04ad14799be32dcac29048b37?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230327T193506Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=apitable%2F20230327%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=be3bbfb9e7587c2364b5ac707e20923c70de410ed37e068ac5609e16534c5ef2 HTTP/1.1", upstream: "http://10.216.3.5:8080/space/2023/03/27/bc1c6af04ad14799be32dcac29048b37?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230327T193506Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=apitable%2F20230327%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=be3bbfb9e7587c2364b5ac707e20923c70de410ed37e068ac5609e16534c5ef2", host: "10.35.158.174", referrer: "http://10.35.158.174/workbench/dst7A37WKRMty6DEjW/viwLATeHohDAB"
gateway_1            | {"@timestamp":"2023-03-28T03:36:06+08:00","@source":"10.216.3.6","@nginx_fields":{"remote_addr":"172.18.113.0","body_bytes_sent":"566","request_time":"60.040","status":"504","host":"10.35.158.174","uri":"/space/2023/03/27/bc1c6af04ad14799be32dcac29048b37","server":"127.0.0.1","request_uri":"/space/2023/03/27/bc1c6af04ad14799be32dcac29048b37?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230327T193506Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3599&X-Amz-Credential=apitable%2F20230327%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=be3bbfb9e7587c2364b5ac707e20923c70de410ed37e068ac5609e16534c5ef2","request_method":"PUT","http_referrer":"http://10.35.158.174/workbench/dst7A37WKRMty6DEjW/viwLATeHohDAB","body_bytes_sent":"566","http_x_forwarded_for":"","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36","upstream_response_time":"60.000","upstream_status":"504","upstream_addr":"10.216.3.5:8080"}}
web-server_1         | Error: aborted
web-server_1         |     at connResetException (node:internal/errors:692:14)
web-server_1         |     at abortIncoming (node:_http_server:602:17)
web-server_1         |     at socketOnClose (node:_http_server:596:3)
web-server_1         |     at Socket.emit (node:events:539:35)
web-server_1         |     at Socket.emit (node:domain:475:12)
web-server_1         |     at TCP.<anonymous> (node:net:709:12)
```

**Comment by ChambersChan** [comment]
Could you tell me about `/asset/upload/preSignedUrl` API response data and modified environment variables?

Under normal circumstances, the upload path should be domain name + bucket name + relative file path, but from the console of your first picture, the complete path loses the bucket name.

**Comment by ratnikov-in** [comment]
Im use ssl certs, add in docker-compose as volume
In logs web server i see error:
```
FetchError: request to https://apitable.mts-corp.ru/assets/space/2022/04/15/9f63510c9c194734ba1c821fa1f611cc?imageView2/1/w/940/h/940/q/100! failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/app/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
FetchError: request to https://apitable.mts-corp.ru/assets/space/2022/01/25/4aa6c029188645cebd8c31f3def205d9 failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/app/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
FetchError: request to https://apitable.mts-corp.ru/assets/space/2021/11/30/854742d76eaa46bba848d80f358f9cdf failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/app/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:527:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
Error: aborted
    at connResetException (node:internal/errors:692:14)
    at abortIncoming (node:_http_server:602:17)
    at socketOnClose (node:_http_server:596:3)
    at Socket.emit (node:events:539:35)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:709:12)
```

Please say me how add correct certs?

**Comment by ratnikov-in** [comment]
If i connect mail server without SSL, config param MAIL_SSL_ENABLE=false in logs i see 
```
220 please start a TLS connection
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; message exception details (1) are:
Failed message 1:
javax.mail.MessagingException: Could not convert socket to TLS; 
```
Maybe create ENV with Certs ?

**Comment by zoe-icu** [comment]
hi
Does this problem still exist? I can't reproduce this issue， can you tell me what email server you use？

**Comment by zoe-icu** [comment]
> If i connect mail server without SSL, config param MAIL_SSL_ENABLE=false in logs i see
> 
> ```
> 220 please start a TLS connection
> org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not convert socket to TLS;
>   nested exception is:
>         javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not convert socket to TLS;
>   nested exception is:
>         javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; message exception details (1) are:
> Failed message 1:
> javax.mail.MessagingException: Could not convert socket to TLS; 
> ```
> 
> Maybe create ENV with Certs ?

hi
Does this problem still exist? I can't reproduce this issue， can you tell me what email server you use？

**Comment by ratnikov-in** [comment]
> > If i connect mail server without SSL, config param MAIL_SSL_ENABLE=false in logs i see
> > ```
> > 220 please start a TLS connection
> > org.springframework.mail.MailSendException: Mail server connection failed; nested exception is javax.mail.MessagingException: Could not convert socket to TLS;
> >   nested exception is:
> >         javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target. Failed messages: javax.mail.MessagingException: Could not convert socket to TLS;
> >   nested exception is:
> >         javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; message exception details (1) are:
> > Failed message 1:
> > javax.mail.MessagingException: Could not convert socket to TLS; 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe create ENV with Certs ?
> 
> hi Does this problem still exist? I can't reproduce this issue， can you tell me what email server you use？

loca server CommuniGate Pro  with out SSL

**Comment by ratnikov-in** [comment]
@zoe-icu please send your config

**Comment by mr-kelly** [comment]
Thank you for the detailed logs. The `UNABLE_TO_VERIFY_LEAF_SIGNATURE` error indicates that the internal Node.js services (`web-server` or `room-server`) cannot verify the SSL certificate of your internal S3/Mail server, likely because it is a self-signed or private CA certificate. A common workaround for local Docker environments is to add the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` to bypass the strict SSL verification, or to mount your private CA certs into the Node containers. Since this is an environment configuration issue, we will close it for now.
