### ISSUE TITLE
make run room-server failed 

### ISSUE THREAD

**Issue by linsheng9731** [apitable/apitable#712]
**Describe the bug**
when run room-server ,  output error messages: 
Type 'typeof HttpConfigService' is not assignable to type 'Type<HttpModuleOptionsFactory>'
```
src/shared/services/java/java.module.ts:31:7 - error TS2322: Type 'typeof HttpConfigService' is not assignable to type 'Type<HttpModuleOptionsFactory>'.

31       useClass: HttpConfigService,
         ~~~~~~~~

  ../../node_modules/@nestjs/axios/dist/interfaces/http-module.interface.d.ts:9:5
    9     useClass?: Type<HttpModuleOptionsFactory>;
          ~~~~~~~~
    The expected type comes from property 'useClass' which is declared here on type 'HttpModuleAsyncOptions'
```
and  another error message: 
```
[Nest] 70141  - 2023/04/15 01:07:10   ERROR [TypeOrmModule] Unable to connect to the database. Message: Access denied for user 'root'@'localhost' (using password: YES). Retrying (1)...
Error: Access denied for user 'root'@'localhost' (using password: YES)
    at Packet.asError (/Users/damon/Documents/WorkSpace/Open-Source/raptor/apitable/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/Users/damon/Documents/WorkSpace/Open-Source/raptor/apitable/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/damon/Documents/WorkSpace/Open-Source/raptor/apitable/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/damon/Documents/WorkSpace/Open-Source/raptor/apitable/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/damon/Documents/WorkSpace/Open-Source/raptor/apitable/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/damon/Documents/WorkSpace/Open-Source/raptor/apitable/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**To Reproduce**
1. make install 
2. make run 
3. input 2  run room-server

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 12.6.4 (21G526)

**Comment by ziqiangai** [comment]
Regarding the first question, I have reproduced the issue you mentioned. Did you delete the `yarn.lock` file in the project path and regenerate it using `make install`? If so, please avoid doing this.

As for the second question, please make sure that the MySQL configuration defined in the `packages/room-server/env/.env.defaults` file matches the account and password of the docker image.
https://github.com/apitable/apitable/blob/bfff268c0b90228e0fdfc4be6d96d648544b1a9b/packages/room-server/env/.env.defaults#L8-L16

**Comment by ziqiangai** [comment]
Hi @linsheng9731 . Is it going well with you?

**Comment by magic-cd** [comment]
> Regarding the first question

I did regenerate it indeed, as I need to install my own dependencies. Can you kindly tell me why this happened? This would help me to solve the problem easily. Thank you.

**Comment by arucil** [comment]
> > Regarding the first question
> 
> I did regenerate it indeed, as I need to install my own dependencies. Can you kindly tell me why this happened? This would help me to solve the problem easily. Thank you.

This is because `package.json` in room-server does not pin versions of most dependencies, but `yarn.lock` does. When regenerating `yarn.lock`, yarn will choose the latest versions conformant to `package.json`, for example, when a dependency is `^7.2.3`, yarn will choose `7.5.7` (if it is the latest version under 8.0.0), however the old `yarn.lock` may specify `7.2.5` (because at the time room-server was developed, this was the latest version), and 7.5.7 may be incompatible with 7.2.5. So it may cause compatibility problem if you regenerate `yarn.lock`. If you want to add your dependency, just run `yarn add XXX`, there is no need to delete yarn.lock.
