### ISSUE TITLE
fix: BUG...

### ISSUE THREAD

**Issue by mailzhaomx** [apitable/apitable#765]
**Describe the bug**

**To Reproduce**

**Expected behavior**
通过接口获取某个单元格数据所在的行号，再利用行号和列标题确定想要写入内容的单元格，报错信息如下：
【 API Server Error: 502
Traceback (most recent call last):
  File "C:\Program Files (x86)\ShadowBot\shadowbot-5.10.40\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\ShadowBot\shadowbot-5.10.40\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\ShadowBot\shadowbot-5.10.40\python\lib\site-packages\xbot_interpreter.py", line 87, in <module>
    main()
  File "C:\Program Files (x86)\ShadowBot\shadowbot-5.10.40\python\lib\site-packages\xbot_interpreter.py", line 47, in main
    try:
  File "C:\Users\admin\AppData\Local\ShadowBot\users\b8830dec-901c-4d25-b53f-05e9afea1c0c\apps\b4ad80e6-6215-40a2-8e68-7c3bb760ef37\xbot_robot\main.py", line 62, in main
    ], _block=("main", 19, "查找维格表数据所在行"))
  File "<string>", line 89, in wrapper
  File "<string>", line 84, in wrapper
  File "<string>", line 82, in run
  File "C:\Users\admin\AppData\Local\ShadowBot\users\b8830dec-901c-4d25-b53f-05e9afea1c0c\apps\b4ad80e6-6215-40a2-8e68-7c3bb760ef37\xbot_extensions\activity_aacccc\process5.py", line 25, in main
    }, _block=("查找维格表数据所在行", 1, "调用模块"))
  File "<string>", line 89, in wrapper
  File "<string>", line 84, in wrapper
  File "<string>", line 37, in invoke_module
  File "C:\Users\admin\AppData\Local\ShadowBot\users\b8830dec-901c-4d25-b53f-05e9afea1c0c\apps\b4ad80e6-6215-40a2-8e68-7c3bb760ef37\xbot_extensions\activity_aacccc\functions.py", line 42, in return_record_id_for_specified_field_containing_specified_text
    book = datasheet.records.get(**{field_name: content_to_search_for})
  File "C:\Users\admin\AppData\Local\ShadowBot\users\b8830dec-901c-4d25-b53f-05e9afea1c0c\apps\b4ad80e6-6215-40a2-8e68-7c3bb760ef37\venv\lib\site-packages\vika\datasheet\record_manager.py", line 105, in get
    resp: GETRecordResponse = self._dst.get_records(**kwargs)
  File "C:\Users\admin\AppData\Local\ShadowBot\users\b8830dec-901c-4d25-b53f-05e9afea1c0c\apps\b4ad80e6-6215-40a2-8e68-7c3bb760ef37\venv\lib\site-packages\vika\datasheet\datasheet.py", line 109, in get_records
    return handle_response(resp, GETRecordResponse)
  File "C:\Users\admin\AppData\Local\ShadowBot\users\b8830dec-901c-4d25-b53f-05e9afea1c0c\apps\b4ad80e6-6215-40a2-8e68-7c3bb760ef37\venv\lib\site-packages\vika\utils.py", line 71, in handle_response
    raise ServerError(f"API Server Error: {resp.status_code}")
vika.exceptions.ServerError: API Server Error: 502
】

**Screenshots**

代码如下：
![image](https://user-images.githubusercontent.com/64526316/236753247-ea33d2ed-639a-4abf-b28b-c1b8d3c0632c.png)

数据如下：
![image](https://user-images.githubusercontent.com/64526316/236753554-b32bbfae-b8fb-4f8f-9a14-07cb3a27ceae.png)

需求如下：
找到指定订单编号所在行号，利用行号在状态列相应单元格写入 进行中 3个字

报错如下：
![63860c8f4d845b56d9eac8566952962](https://user-images.githubusercontent.com/64526316/236751829-cc744ef1-b5f1-42a4-a4ca-5a3be8e2bf71.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mr-kelly** [comment]
Can you provide steps to reproduce the result? Which software you are using? like:


Go to '...'
Click on '....'
Scroll down to '....'
See error
